// The Tunnel Cat Project
// Copyright (C) NavLink, 2026
// Лицензировано под лицензией Apache 2.0

package main

import (
	"net/http"
	"strconv"
	"strings"
)

type anonBootstrapPageData struct {
	Token   string
	Entries []AnonAllowlistEntry
}

// adminAnonBootstrapPage renders GET /admin/anon-bootstrap.
func (h *handler) adminAnonBootstrapPage(w http.ResponseWriter, r *http.Request) {
	flashOK := ""
	if r.URL.Query().Get("regenerated") == "1" {
		flashOK = "Token regenerated."
	}
	h.renderAnonBootstrapPageFull(w, r, "", flashOK)
}

func (h *handler) renderAnonBootstrapPage(w http.ResponseWriter, r *http.Request, flash string) {
	h.renderAnonBootstrapPageFull(w, r, flash, "")
}

func (h *handler) renderAnonBootstrapPageFull(w http.ResponseWriter, r *http.Request, flash, flashOK string) {
	token, err := h.db.getOrCreateAnonBootstrapToken()
	if err != nil {
		logWarnf("anon-bootstrap page: token: %v", err)
	}
	entries, err := h.db.listAnonAllowlistEntries()
	if err != nil {
		logWarnf("anon-bootstrap page: entries: %v", err)
	}
	u := h.currentUser(r)
	h.renderPage(w, "admin_anon_bootstrap.html", pageData{
		User:    u,
		Data:    anonBootstrapPageData{Token: token, Entries: entries},
		Flash:   flash,
		FlashOK: flashOK,
	})
}

// adminAnonBootstrapAdd handles POST /admin/anon-bootstrap/add.
func (h *handler) adminAnonBootstrapAdd(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "bad request", http.StatusBadRequest)
		return
	}
	entryType := r.FormValue("type")
	value := strings.TrimSpace(r.FormValue("value"))
	if entryType != "domain" && entryType != "wildcard" && entryType != "cidr" {
		http.Error(w, "invalid type", http.StatusBadRequest)
		return
	}
	if value == "" {
		http.Redirect(w, r, "/admin/anon-bootstrap", http.StatusFound)
		return
	}
	if err := h.db.addAnonAllowlistEntry(entryType, value); err != nil {
		logWarnf("anon-bootstrap add: %v", err)
	}
	logInfof("anon-bootstrap: added type=%s value=%s", entryType, value)
	http.Redirect(w, r, "/admin/anon-bootstrap", http.StatusFound)
}

// adminAnonBootstrapDelete handles POST /admin/anon-bootstrap/delete.
func (h *handler) adminAnonBootstrapDelete(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "bad request", http.StatusBadRequest)
		return
	}
	id, err := strconv.ParseInt(r.FormValue("id"), 10, 64)
	if err != nil {
		http.Error(w, "bad id", http.StatusBadRequest)
		return
	}
	if err := h.db.deleteAnonAllowlistEntry(id); err != nil {
		logWarnf("anon-bootstrap delete %d: %v", id, err)
	}
	logInfof("anon-bootstrap: deleted id=%d", id)
	http.Redirect(w, r, "/admin/anon-bootstrap", http.StatusFound)
}

// adminAnonBootstrapRegenerate handles POST /admin/anon-bootstrap/regenerate.
// Invalidates every previously-built client's embedded token the moment
// exits next refresh their cache (up to anonBootstrapRefreshInterval later,
// see snc-exit/anon_bootstrap.go) -- use when a token is suspected leaked
// beyond what's tolerable, or as routine hygiene between client releases.
func (h *handler) adminAnonBootstrapRegenerate(w http.ResponseWriter, r *http.Request) {
	u := h.currentUser(r)
	by := "admin"
	if u != nil {
		by = u.Username
	}
	if _, err := h.db.regenerateAnonBootstrapToken(by); err != nil {
		logWarnf("anon-bootstrap regenerate: %v", err)
		h.renderAnonBootstrapPage(w, r, "Error: could not regenerate token.")
		return
	}
	logInfof("anon-bootstrap: token regenerated by=%s", by)
	http.Redirect(w, r, "/admin/anon-bootstrap?regenerated=1", http.StatusFound)
}

// apiAnonBootstrap returns the signed anon-bootstrap manifest (token + allowlist).
// GET /api/anon-bootstrap — authenticated by exit/control node token.
func (h *handler) apiAnonBootstrap(w http.ResponseWriter, r *http.Request) {
	token := r.Header.Get("X-Node-Token")
	if token == "" {
		jsonErr(w, "X-Node-Token required", http.StatusUnauthorized)
		return
	}
	node, err := h.db.nodeByToken(token)
	if err != nil || node == nil || (node.Type != "exit" && node.Type != "control") {
		jsonErr(w, "unauthorized", http.StatusUnauthorized)
		return
	}
	bootstrapToken, err := h.db.getOrCreateAnonBootstrapToken()
	if err != nil {
		jsonErr(w, "internal error", http.StatusInternalServerError)
		return
	}
	entries, err := h.db.listAnonAllowlistEntries()
	if err != nil {
		jsonErr(w, "internal error", http.StatusInternalServerError)
		return
	}
	data, err := h.signer.signAnonBootstrap(bootstrapToken, entries)
	if err != nil {
		jsonErr(w, "signing error", http.StatusInternalServerError)
		return
	}
	logInfof("anon-bootstrap: serving to node=%s count=%d", node.Addr, len(entries))
	w.Header().Set("Content-Type", "application/json")
	w.Write(data) //nolint:errcheck
}
