// The Tunnel Cat Project
// Copyright (C) NavLink, 2026
// Лицензировано под лицензией Apache 2.0

package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"errors"
	"fmt"
	"sync"
	"time"

	"golang.org/x/crypto/blake2b"
	"golang.org/x/crypto/chacha20poly1305"
)

const (
	sessionValidateTTL   = 15 * time.Minute // re-validate with Camerlengo every 15 min
	sessionRetryCooldown = 1 * time.Minute  // cooldown between failed re-validation attempts
	sessionStaleTTL      = 3 * time.Hour    // keep session valid for 3 h without Camerlengo
	sessionRefreshPause  = 10 * time.Second // max 1 querySession call/10s, prevents overloading auth server

	multiDeviceWindow = 10 * time.Second // concurrent logins within this window trigger a warning
	warnCooldown      = 1 * time.Hour    // minimum interval between warnings per key
	maxWarnings       = 3                // warnings before account is suspended
)

// keyDeviceSeen tracks the last device that logged in with a given key.
type keyDeviceSeen struct {
	deviceID string
	at       time.Time
}

// SessionManager manages VPN client sessions: issues SNC tokens, caches
// Camerlengo sessions, and periodically re-validates / re-logins.
type SessionManager struct {
	db     *DB
	auth   *authClient
	encKey [32]byte

	seenMu   sync.Mutex
	lastSeen map[string]keyDeviceSeen // keyID → last device seen
}

func newSessionManager(db *DB, auth *authClient, sk *signingKey) *SessionManager {
	sm := &SessionManager{
		db:       db,
		auth:     auth,
		lastSeen: make(map[string]keyDeviceSeen),
	}
	sm.encKey = deriveEncKey(sk.priv)
	return sm
}

// deriveEncKey produces a 32-byte symmetric key from the arbiter's Ed25519 seed.
func deriveEncKey(priv ed25519.PrivateKey) [32]byte {
	h, _ := blake2b.New256(nil)
	h.Write(priv.Seed())
	h.Write([]byte("snc-arbiter-pwd-enc-v1"))
	var key [32]byte
	copy(key[:], h.Sum(nil))
	return key
}

func (sm *SessionManager) encrypt(data []byte) ([]byte, error) {
	aead, err := chacha20poly1305.New(sm.encKey[:])
	if err != nil {
		return nil, err
	}
	nonce := make([]byte, aead.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return nil, err
	}
	return append(nonce, aead.Seal(nil, nonce, data, nil)...), nil
}

func (sm *SessionManager) decrypt(enc []byte) ([]byte, error) {
	aead, err := chacha20poly1305.New(sm.encKey[:])
	if err != nil {
		return nil, err
	}
	ns := aead.NonceSize()
	if len(enc) < ns+aead.Overhead() {
		return nil, errors.New("ciphertext too short")
	}
	return aead.Open(nil, enc[:ns], enc[ns:], nil)
}

// LoginOpts carries optional device-binding information supplied by the client
// during the verifyPassword handshake.  All fields are optional.
type LoginOpts struct {
	KeyID      string // key_id from the encrypted key blob
	DeviceID   string // stable per-device UUID generated by the client
	DeviceName string // human-readable device label (e.g. "Windows PC", "Android")
}

// Login validates credentials against Camerlengo, stores a new SNC session,
// and returns the opaque SNC token.
//
// If opts is non-nil and opts.KeyID is set, device-binding and key-enabled
// checks are enforced; unknown key_ids are allowed (legacy key without a DB
// record).
func (sm *SessionManager) Login(username, password string, opts *LoginOpts) (string, error) {
	camSession, err := sm.auth.login(username, password)
	if err != nil {
		// Camerlengo rejected/errored on this attempt. An already-issued
		// session is allowed to keep working for up to sessionStaleTTL (3h)
		// without Camerlengo (see refreshOne) — apply the same policy to a
		// *fresh* login: if this exact (username, password) produced a valid
		// session within the last sessionStaleTTL, reuse it instead of
		// rejecting outright. Without this, a Camerlengo hiccup (or a benign
		// race from several control nodes logging the same account in
		// concurrently) permanently fails a brand-new connection attempt
		// even though the account is known-good — confirmed as a real,
		// reproduced complaint on 2026-08-09 (kam2312@mail.ru: intermittent
		// "Invalid username or password" interleaved with successful logins
		// for the identical credentials, seconds apart).
		recent, rerr := sm.db.getRecentSessionByUsername(username)
		if rerr != nil || recent == nil || time.Since(recent.ValidatedAt) >= sessionStaleTTL {
			return "", err
		}
		pwd, derr := sm.decrypt(recent.EncPassword)
		if derr != nil || string(pwd) != password {
			return "", err
		}
		var reqDevice string
		if opts != nil {
			reqDevice = opts.DeviceID
		}
		logWarnf("sessions: login: Camerlengo error for %s device=%s (%v) — falling back to session from device=%q(%s) validated %s ago",
			username, reqDevice, err, recent.DeviceName, recent.DeviceID, time.Since(recent.ValidatedAt).Round(time.Second))
		camSession = recent.CamSession
	}

	// Device-binding checks when a key_id is provided.
	if opts != nil && opts.KeyID != "" {
		// Check whether the user account is enabled.
		ok, err := sm.db.IsUserEnabled(username)
		if err != nil {
			logWarnf("sessions: IsUserEnabled %s: %v", username, err)
		} else if !ok {
			return "", fmt.Errorf("account disabled")
		}

		key, err := sm.db.GetKey(opts.KeyID)
		if err != nil {
			logWarnf("sessions: GetKey %s: %v", opts.KeyID, err)
		}
		if key != nil {
			if !key.Enabled {
				return "", fmt.Errorf("key disabled")
			}
			if !key.UnlimitedDevices {
				if key.DeviceID == "" && opts.DeviceID != "" {
					// First activation: bind the device.
					if err := sm.db.UpsertKeyDevice(opts.KeyID, opts.DeviceID, opts.DeviceName); err != nil {
						logWarnf("sessions: UpsertKeyDevice %s: %v", opts.KeyID, err)
					}
				}
				// Multi-device warning/auto-suspend disabled 2026-08-05 -- see
				// checkMultiDevice's doc comment for why.
			}
			if err := sm.db.TouchKeyLastSeen(opts.KeyID); err != nil {
				logWarnf("sessions: TouchKeyLastSeen %s: %v", opts.KeyID, err)
			}
		}
		// key == nil means no DB record (legacy key issued before this feature).
		// Allow login without restriction.
	}

	// Ensure user exists and get/generate their immutable ClientID.
	u, err := sm.db.getOrCreateUser(username)
	if err != nil {
		return "", fmt.Errorf("get user: %w", err)
	}

	encPwd, err := sm.encrypt([]byte(password))
	if err != nil {
		return "", err
	}

	token, err := genToken()
	if err != nil {
		return "", err
	}

	var deviceID, deviceName string
	if opts != nil {
		deviceID, deviceName = opts.DeviceID, opts.DeviceName
	}

	now := time.Now()
	if err := sm.db.createSession(token, username, u.ClientID, deviceID, deviceName, encPwd, camSession, now); err != nil {
		return "", err
	}

	logInfof("sessions: login user=%s client_id=%s device=%q(%s) token=%.8s…", username, u.ClientID, deviceName, deviceID, token)
	return token, nil
}

// LoginWithKey creates an SNC session for a user authenticated via AuthSig
// (key-based authentication without a Camerlengo password check).
// The caller must verify the AuthSig before invoking this method.
func (sm *SessionManager) LoginWithKey(username string, opts *LoginOpts) (string, error) {
	if opts != nil && opts.KeyID != "" {
		ok, err := sm.db.IsUserEnabled(username)
		if err != nil {
			logWarnf("sessions: LoginWithKey IsUserEnabled %s: %v", username, err)
		} else if !ok {
			return "", fmt.Errorf("account disabled")
		}

		key, err := sm.db.GetKey(opts.KeyID)
		if err != nil {
			logWarnf("sessions: LoginWithKey GetKey %s: %v", opts.KeyID, err)
		}
		if key != nil {
			if !key.Enabled {
				return "", fmt.Errorf("key disabled")
			}
			if !key.UnlimitedDevices {
				if key.DeviceID == "" && opts.DeviceID != "" {
					if err := sm.db.UpsertKeyDevice(opts.KeyID, opts.DeviceID, opts.DeviceName); err != nil {
						logWarnf("sessions: LoginWithKey UpsertKeyDevice %s: %v", opts.KeyID, err)
					}
				}
				// Multi-device warning/auto-suspend disabled 2026-08-05 -- see
				// checkMultiDevice's doc comment for why.
			}
			if err := sm.db.TouchKeyLastSeen(opts.KeyID); err != nil {
				logWarnf("sessions: LoginWithKey TouchKeyLastSeen %s: %v", opts.KeyID, err)
			}
		}
	}

	u, err := sm.db.getOrCreateUser(username)
	if err != nil {
		return "", fmt.Errorf("get user: %w", err)
	}

	token, err := genToken()
	if err != nil {
		return "", err
	}

	var deviceID, deviceName string
	if opts != nil {
		deviceID, deviceName = opts.DeviceID, opts.DeviceName
	}

	now := time.Now()
	// cam_session is empty for key-auth sessions; refreshOne skips re-validation for them.
	if err := sm.db.createSession(token, username, u.ClientID, deviceID, deviceName, []byte{}, "", now); err != nil {
		return "", err
	}

	logInfof("sessions: key-auth login user=%s client_id=%s device=%q(%s) token=%.8s…", username, u.ClientID, deviceName, deviceID, token)
	return token, nil
}

// LoginAsProxy validates credentials against Camerlengo and issues a session
// token for the user — without requiring a key_id or device binding.
//
// Used by BlackBadger proxy instances: the proxy authenticates the SOCKS5 user,
// obtains a token for them, and forwards that token in X-Session so that all
// tunnelled traffic is attributed to the correct user account.
func (sm *SessionManager) LoginAsProxy(username, password string) (string, error) {
	// Validate credentials via Camerlengo (same as normal Login).
	camSession, err := sm.auth.login(username, password)
	if err != nil {
		return "", err
	}

	// Respect account-level suspension.
	ok, err := sm.db.IsUserEnabled(username)
	if err != nil {
		logWarnf("sessions: LoginAsProxy IsUserEnabled %s: %v", username, err)
	} else if !ok {
		return "", fmt.Errorf("account disabled")
	}

	u, err := sm.db.getOrCreateUser(username)
	if err != nil {
		return "", fmt.Errorf("get user: %w", err)
	}

	encPwd, err := sm.encrypt([]byte(password))
	if err != nil {
		return "", err
	}

	token, err := genToken()
	if err != nil {
		return "", err
	}

	now := time.Now()
	// No device info: BlackBadger proxy logins authenticate a SOCKS5 user on
	// the proxy's behalf, not a distinct SNC client device.
	if err := sm.db.createSession(token, username, u.ClientID, "", "BlackBadger proxy", encPwd, camSession, now); err != nil {
		return "", err
	}

	logInfof("sessions: proxy-login user=%s client_id=%s token=%.8s…", username, u.ClientID, token)
	return token, nil
}

// Validate returns the username and ClientID for a known SNC token, and
// whether the request must be rejected outright.
//
// denied=true is a real, local, deterministic verdict -- callers (exits) must
// reject (404) it and are expected to *remember* that verdict across their
// own cache TTL, even through a later arbiter outage (see snc-exit/auth.go's
// validateSession: a stale cache entry must keep returning its last known
// denied value, never silently reset to false just because a fresh check
// wasn't possible). Two things can produce denied=true here, and both are
// fully local to this arbiter -- neither depends on Camerlengo being
// reachable right now:
//   - no session presented, or none found for the given token (never issued,
//     or expired and pruned -- see StartRefresher/refreshOne: an existing
//     session is kept locally for up to sessionStaleTTL=3h without a
//     successful Camerlengo re-check before being deleted, which is exactly
//     the "already-established sessions stay valid without Camerlengo"
//     window the spec calls for; past that window, "not found" is the
//     correct, deliberate outcome, not an ambiguous one)
//   - the account exists but was locally suspended by an admin
//     (IsUserEnabled) -- this is an arbiter-local flag, also nothing to do
//     with Camerlengo
//
// denied=false with empty username should be unreachable in normal
// operation (every "unknown token" path above now returns denied=true) --
// it's kept as the fallback for unexpected local-DB errors, where the
// conservative choice is "don't wrongly deny on our own storage hiccup."
func (sm *SessionManager) Validate(token string) (username, clientID, deviceID string, denied bool) {
	if token == "" {
		// No session presented at all -- as deterministic and local a verdict
		// as it gets, same reasoning as the "not found" case below.
		return "", "", "", true
	}
	s, err := sm.db.getSession(token)
	if err != nil {
		logWarnf("sessions: validate db error: %v", err)
		return "", "", "", false
	}
	if s == nil {
		// Token not found: never issued, or aged out past sessionStaleTTL
		// (see the doc comment above) -- either way this arbiter has looked
		// and there is no such session, a real verdict, not "unknown."
		return "", "", "", true
	}

	// Check whether the account is still enabled.
	ok, err := sm.db.IsUserEnabled(s.Username)
	if err != nil {
		logWarnf("sessions: validate IsUserEnabled %s: %v", s.Username, err)
		// DB error — fall through and allow rather than wrongly denying.
	} else if !ok {
		logInfof("sessions: validate denied user=%s token=%.8s…", s.Username, token)
		return "", "", "", true
	}

	// Touch validated_at so the session stays alive while the client is active.
	if err := sm.db.touchSession(token, time.Now()); err != nil {
		logWarnf("sessions: touchSession %s: %v", s.Username, err)
	}

	return s.Username, s.ClientID, s.DeviceID, false
}

// StartRefresher starts the background goroutine that periodically re-validates
// all cached sessions with Camerlengo and re-logs in when needed.
func (sm *SessionManager) StartRefresher() {
	go sm.refreshLoop()
}

func (sm *SessionManager) refreshLoop() {
	ticker := time.NewTicker(sessionRetryCooldown)
	defer ticker.Stop()
	for range ticker.C {
		sm.refreshAll()
	}
}

func (sm *SessionManager) refreshAll() {
	sessions, err := sm.db.listSessions()
	if err != nil {
		logWarnf("sessions: list error: %v", err)
		return
	}
	now := time.Now()
	for _, s := range sessions {
		sm.refreshOne(s, now)
	}
}

func (sm *SessionManager) refreshOne(s *Session, now time.Time) {
	// Fresh — no action needed.
	if now.Sub(s.ValidatedAt) < sessionValidateTTL {
		return
	}

	// Too stale — session is dead, force re-login on next client connection.
	if now.Sub(s.ValidatedAt) > sessionStaleTTL {
		logInfof("sessions: expired user=%s device=%q(%s) token=%.8s…", s.Username, s.DeviceName, s.DeviceID, s.Token)
		sm.db.deleteSession(s.Token) //nolint:errcheck
		return
	}

	// Key-auth sessions have no Camerlengo session — let them expire naturally.
	if s.CamSession == "" {
		return
	}

	// Still within stale window but cooling down from last attempt.
	if now.Sub(s.LastAttempt) < sessionRetryCooldown {
		return
	}

	// Mark attempt before network call.
	sm.db.touchLastAttempt(s.Token, now) //nolint:errcheck

	// Rate-limit: prevents a burst of simultaneous calls after a restart when
	// all sessions have stale ValidatedAt timestamps.
	time.Sleep(sessionRefreshPause)

	// Try to validate the existing Camerlengo session.
	username, err := sm.auth.querySession(s.CamSession)
	if err != nil {
		logWarnf("sessions: validate error user=%s device=%q(%s): %v — keeping stale", s.Username, s.DeviceName, s.DeviceID, err)
		return
	}

	if username != "" {
		// Still valid.
		sm.db.updateCamSession(s.Token, s.CamSession, now) //nolint:errcheck
		logDebugf("sessions: refreshed user=%s device=%q(%s) token=%.8s…", s.Username, s.DeviceName, s.DeviceID, s.Token)
		return
	}

	// Camerlengo session expired — re-login with stored credentials.
	pwd, err := sm.decrypt(s.EncPassword)
	if err != nil {
		logWarnf("sessions: decrypt error user=%s device=%q(%s): %v", s.Username, s.DeviceName, s.DeviceID, err)
		return
	}

	newCam, err := sm.auth.login(s.Username, string(pwd))
	if err != nil {
		logWarnf("sessions: re-login failed user=%s device=%q(%s): %v — keeping stale", s.Username, s.DeviceName, s.DeviceID, err)
		return
	}

	sm.db.updateCamSession(s.Token, newCam, now) //nolint:errcheck
	logInfof("sessions: re-login OK user=%s device=%q(%s) token=%.8s…", s.Username, s.DeviceName, s.DeviceID, s.Token)
}

// ── Multi-device detection ────────────────────────────────────────────────────

// checkMultiDevice records the current deviceID for keyID and triggers a warning
// if a different device is seen within multiDeviceWindow of the previous login.
// The warning is issued asynchronously to avoid blocking the login path.
//
// Not called anywhere as of 2026-08-05 (see call sites in LoginWithKey/etc.) -- this
// whole mechanism existed to enforce the one-key-per-paid-device billing model, which
// no longer exists (every key is perpetual/free now -- see the same day's paid_until
// cleanup). It also had no path back from a false-positive suspension:
// bitehard2017@gmail.com's account was found stuck disabled from a stale warning even
// after they'd correctly split their key across devices, with nothing to ever
// re-evaluate or clear it automatically. Left in place (not deleted) in case per-device
// limits come back under a real billing model later.
func (sm *SessionManager) checkMultiDevice(keyID, username, deviceID string) {
	sm.seenMu.Lock()
	prev, hasPrev := sm.lastSeen[keyID]
	sm.lastSeen[keyID] = keyDeviceSeen{deviceID: deviceID, at: time.Now()}
	sm.seenMu.Unlock()

	if hasPrev && prev.deviceID != deviceID && time.Since(prev.at) <= multiDeviceWindow {
		go sm.maybeWarn(keyID, username)
	}
}

// maybeWarn issues a per-user warning notification and, after maxWarnings,
// suspends the account.  Warnings are throttled to one per warnCooldown per key.
func (sm *SessionManager) maybeWarn(keyID, username string) {
	count, lastAt, err := sm.db.GetKeyWarnState(keyID)
	if err != nil {
		logWarnf("sessions: GetKeyWarnState %s: %v", keyID, err)
		return
	}
	if count >= maxWarnings {
		return // already suspended
	}
	if lastAt > 0 && time.Since(time.Unix(lastAt, 0)) < warnCooldown {
		return // throttle: one warning per hour per key
	}

	newCount, err := sm.db.BumpKeyWarn(keyID)
	if err != nil {
		logWarnf("sessions: BumpKeyWarn %s: %v", keyID, err)
		return
	}

	msg := multiDeviceWarningMessage(newCount)
	if err := sm.db.addUserNotification(username, msg); err != nil {
		logWarnf("sessions: addUserNotification %s: %v", username, err)
	}
	logWarnf("security: multi-device key=%s user=%s warning=%d/%d", keyID, username, newCount, maxWarnings)

	if newCount >= maxWarnings {
		if err := sm.db.SetUserEnabled(username, false); err != nil {
			logWarnf("sessions: suspend user %s: %v", username, err)
		}
		logWarnf("security: account suspended user=%s after %d multi-device warnings", username, maxWarnings)
	}
}

func multiDeviceWarningMessage(count int) string {
	switch count {
	case 1:
		return "You are using the same key on multiple devices. This violates the key usage policy. Please obtain a separate key for each device."
	case 2:
		return "You are using one key on multiple devices. Please obtain additional keys, otherwise we will be forced to suspend your account."
	default:
		return "Your account has been suspended due to using one key on multiple devices. Please contact support for reactivation."
	}
}
