// The Tunnel Cat Project
// Copyright (C) NavLink, 2026
// Лицензировано под лицензией Apache 2.0

// Code generated by tunnel_cat/logschema/gen.py from events.yaml. DO NOT EDIT.
// Edit tunnel_cat/logschema/events.yaml and re-run gen.py instead.

package logevent

// Event is a structured log event's numeric id, prefixed ahead of its
// CBOR attribute map on the wire (see binlog.FormatStructured) so a
// scanner can read event identity without decoding CBOR at all.
type Event uint32

const (
	// One ShouldBypass() call's outcome -- whether an outbound address was routed direct (bypassing the tunnel) or not, and why.
	EventBypassDecision Event = 1 // 'bypass.decision'
	// TunnelDialer.Dial() beginning one connection attempt.
	EventTunnelDialStart Event = 2 // 'tunnel.dial_start'
	// forwardOutbound's per-destination routing choice for a UDP datagram.
	EventUdpAssocRoutingDecision Event = 3 // 'udp_assoc.routing_decision'
	// One send() attempt's outcome inside TunnelDialer.Dial (seq 0 = connection establishment).
	EventTunnelPostResult Event = 4 // 'tunnel.post_result'
	// One retry of the initial connection probe after a transient network error.
	EventTunnelDialRetry Event = 5 // 'tunnel.dial_retry'
	// TunnelDialer.Dial() succeeded -- connection is live.
	EventTunnelDialEstablished Event = 6 // 'tunnel.dial_established'
	// tunnelConn's streaming loop successfully (re)opened its stream.
	EventSessionStreamOpened Event = 7 // 'session.stream_opened'
	// tunnelConn's streaming loop failed to open a stream (not yet giving up).
	EventSessionStreamOpenError Event = 8 // 'session.stream_open_error'
	// Stream open got HTTP 404 from the exit -- connection already closed remotely, no point retrying.
	EventSessionStreamGiveup404 Event = 9 // 'session.stream_giveup_404'
	// tunnelConn's streaming loop gave up for a reason other than a 404.
	EventSessionStreamGiveup Event = 10 // 'session.stream_giveup'
	// Stream was renewed (fresh streamFn) after flap/error retries exhausted.
	EventSessionStreamRenewed Event = 11 // 'session.stream_renewed'
	// Stream flapped (opened then immediately closed) -- counts toward the flap-retry budget.
	EventSessionStreamFlapped Event = 12 // 'session.stream_flapped'
	// Stream closed cleanly and is being reopened (normal keep-alive cycling, not an error).
	EventSessionStreamClosedReopening Event = 13 // 'session.stream_closed_reopening'
	// A control node was marked data-plane-dead until a future time (still tried again after that).
	EventRouterControlMarkedDead Event = 14 // 'router.control_marked_dead'
	// A control's UDP data plane failed -- downgraded to TCP for 5 minutes.
	EventRouterUdpDowngraded Event = 15 // 'router.udp_downgraded'
	// Router finished building its ranked path list for this refresh cycle.
	EventRouterPathsBuilt Event = 16 // 'router.paths_built'
	// One entry in the path list router.paths_built just reported (one event per path, same cycle).
	EventRouterPathEntry Event = 17 // 'router.path_entry'
	// A UDP destination stopped getting responses on the bypass path and switched to tunnel.
	EventUdpAssocFallbackToTunnel Event = 18 // 'udp_assoc.fallback_to_tunnel'
	// A UDP destination was pinned to a specific control dialer for the life of its session.
	EventUdpAssocPinnedDialer Event = 19 // 'udp_assoc.pinned_dialer'
	// ProtectClient beginning a (re)connect to its Kotlin-side Unix socket.
	EventProtectReconnecting Event = 20 // 'protect.reconnecting'
	// ProtectClient's reconnect succeeded. No event fires if it failed -- the caller logs its own error separately.
	EventProtectReconnected Event = 21 // 'protect.reconnected'
	// The watchdog force-closed a protect call that had been hung for over 5s.
	EventProtectWatchdogHung Event = 22 // 'protect.watchdog_hung'
	// protectFDLocked had no working socket (reconnect failed) -- fd will NOT be protected, i.e. it may leak outside the VPN.
	EventProtectNoSocket Event = 23 // 'protect.no_socket'
	// The send or ack half of one protect round-trip failed.
	EventProtectIoError Event = 24 // 'protect.io_error'
	// Reconnect attempted after an io_error, and its own outcome.
	EventProtectReconnectAfterError Event = 25 // 'protect.reconnect_after_error'
	// Kotlin side explicitly rejected a protect request (ack byte was not 1).
	EventProtectNack Event = 26 // 'protect.nack'
	// One fd successfully protected -- the hot-path success case, fires on every outbound socket.
	EventProtectOk Event = 27 // 'protect.ok'
	// SNCVpnService.onCreate() ran.
	EventAndroidVpnCreated Event = 28 // 'android.vpn_created'
	// onStartCommand received -- either a stop request or a (re)start.
	EventAndroidVpnStartCommand Event = 29 // 'android.vpn_start_command'
	// startVpn() beginning one connection attempt.
	EventAndroidVpnStartBegin Event = 30 // 'android.vpn_start_begin'
	// startVpn()'s VpnService.Builder.establish() succeeded -- TUN fd is live.
	EventAndroidVpnTunEstablished Event = 31 // 'android.vpn_tun_established'
	// startVpn() gave up after exhausting establish() retry attempts.
	EventAndroidVpnStartFailed Event = 32 // 'android.vpn_start_failed'
	// The Go snc-core subprocess startVpn() launched has exited.
	EventAndroidVpnProcessExited Event = 33 // 'android.vpn_process_exited'
	// startVpn() caught an exception during setup or run.
	EventAndroidVpnStartException Event = 34 // 'android.vpn_start_exception'
	// stopVpn() was called.
	EventAndroidVpnStop Event = 35 // 'android.vpn_stop'
	// Android called onRevoke() -- another app or the user revoked VPN permission.
	EventAndroidVpnRevoke Event = 36 // 'android.vpn_revoke'
	// SNCVpnService.onDestroy() ran.
	EventAndroidVpnDestroyed Event = 37 // 'android.vpn_destroyed'
	// UpdateChecker.start() was called.
	EventUpdateCheckerStarted Event = 38 // 'update.checker_started'
	// One check() call threw inside the poll loop -- loop continues after this.
	EventUpdateCheckError Event = 39 // 'update.check_error'
	// check() skipped this cycle before contacting any control.
	EventUpdateCheckSkipped Event = 40 // 'update.check_skipped'
	// check() beginning a poll cycle against known controls.
	EventUpdateCheckStart Event = 41 // 'update.check_start'
	// A control's /client-android-version endpoint fetch returned nothing.
	EventUpdateFetchFailed Event = 42 // 'update.fetch_failed'
	// A control returned a version string that failed validation.
	EventUpdateInvalidVersion Event = 43 // 'update.invalid_version'
	// A control's remote version is not newer than the running build.
	EventUpdateUpToDate Event = 44 // 'update.up_to_date'
	// A control reported a newer version -- silent download starting.
	EventUpdateAvailable Event = 45 // 'update.available'
	// Silent download/verification exhausted its retries for this version.
	EventUpdateDownloadFailed Event = 46 // 'update.download_failed'
	// An update APK was downloaded, SHA-256-verified, and is ready to install.
	EventUpdateReady Event = 47 // 'update.ready'
	// No control in this poll cycle returned a usable version string.
	EventUpdateNoValidVersion Event = 48 // 'update.no_valid_version'
	// openConnection's direct (protect()'d) attempt failed -- falling back to SOCKS5.
	EventUpdateDirectAttemptFailed Event = 49 // 'update.direct_attempt_failed'
	// One HTTP request to a control's update port failed, either fetching version/sha256/apk text or downloading the APK body.
	EventUpdateHttpFailed Event = 50 // 'update.http_failed'
	// WebView package/version info captured once per WebView creation (2026-08-15 TLS trust investigation).
	EventBrowseWebviewInfo Event = 62 // 'browse.webview_info'
	// onPermissionRequest denied a WebView getUserMedia()-style permission request.
	EventBrowsePermissionDenied Event = 63 // 'browse.permission_denied'
	// shouldOverrideUrlLoading saw a non-http(s) URL scheme (e.g. a "log in via app" intent:// link WebView can't hand off).
	EventBrowseNonHttpScheme Event = 64 // 'browse.non_http_scheme'
	// WebViewClient.onReceivedError fired for the main frame.
	EventBrowseLoadError Event = 65 // 'browse.load_error'
	// WebViewClient.onReceivedSslError fired -- load cancelled either way, this only records why.
	EventBrowseSslError Event = 66 // 'browse.ssl_error'
	// The user tapped the connect/disconnect button.
	EventUiButtonPressed Event = 69 // 'ui.button_pressed'
	// One lifecycle event of SncBackgroundService (the background, non-VPN snc-core instance).
	EventAndroidBgServiceLifecycle Event = 70 // 'android.bg_service_lifecycle'
	// Battery-optimization exemption state at one of the points it's checked/requested.
	EventAndroidBatteryExemptionCheck Event = 161 // 'android.battery_exemption_check'
	// One diagnostic observed while retrying VpnService.Builder.establish().
	EventAndroidVpnEstablishDiag Event = 71 // 'android.vpn_establish_diag'
	// startVpn()'s finally block decided whether to silently reconnect.
	EventAndroidVpnReconnectDecision Event = 72 // 'android.vpn_reconnect_decision'
	// The Kotlin-side protect() Unix socket accept loop hit a non-fatal error.
	EventAndroidProtectLoopError Event = 73 // 'android.protect_loop_error'
	// The Kotlin-side per-app-UID lookup socket accept loop hit a non-fatal error.
	EventAndroidUidLoopError Event = 74 // 'android.uid_loop_error'
	// A ConnectivityManager network callback or registration event fired.
	EventAndroidNetworkEvent Event = 75 // 'android.network_event'
	// Periodic network-diagnostics heartbeat (independent of change events, to catch missed callbacks).
	EventAndroidNetworkHeartbeat Event = 76 // 'android.network_heartbeat'
	// One iteration of the snc.state poll loop threw.
	EventAndroidStateWatchError Event = 77 // 'android.state_watch_error'
	// One attempt (or outcome) of sending an IPC command to the running Go core.
	EventAndroidIpcSend Event = 78 // 'android.ipc_send'
	// One diagnostic checkpoint during main()'s early startup sequence.
	EventWinStartupDiag Event = 79 // 'win.startup_diag'
	// One stage of the watchdog process's own lifecycle, as observed from the main process.
	EventWinWatchdogLifecycle Event = 80 // 'win.watchdog_lifecycle'
	// pickServerURL chose (or failed to find) a control node to try.
	EventWinPickServerUrl Event = 81 // 'win.pick_server_url'
	// One stage of the global control-node Discoverer's lifecycle.
	EventWinDiscovery Event = 82 // 'win.discovery'
	// One stage of processing admin broadcast notifications from the manifest.
	EventWinNotification Event = 83 // 'win.notification'
	// One stage of a per-club (Cat Club/Elite Cat Club) ClubDiscoverer's lifecycle.
	EventWinClubDiscovery Event = 84 // 'win.club_discovery'
	// Outcome of recommending a username for Cat Club membership.
	EventWinClubRecommend Event = 85 // 'win.club_recommend'
	// A manifest received via DHT gossip failed InjectRaw validation.
	EventWinDhtGossipRejected Event = 86 // 'win.dht_gossip_rejected'
	// One stage of the torrent-like content-mirroring subsystem.
	EventWinMirror Event = 87 // 'win.mirror'
	// Outcome of handling a navlink://activate?key=... deep-link launch.
	EventWinDeepLink Event = 88 // 'win.deep_link'
	// One stage of authenticating to a control node, either at startup (auto) or via the login dialog (manual).
	EventWinAuth Event = 89 // 'win.auth'
	// The stable device UUID loaded/generated for key-binding enforcement.
	EventWinDeviceId Event = 90 // 'win.device_id'
	// The DHT node ID loaded or generated for this install.
	EventWinNodeId Event = 91 // 'win.node_id'
	// One stage of the app-lifetime DHT node's setup or its relay-server role.
	EventWinDht Event = 92 // 'win.dht'
	// The client's region was loaded, detected, or explicitly set.
	EventWinGeo Event = 93 // 'win.geo'
	// Outcome of registering the app to launch at Windows startup.
	EventWinAutostart Event = 94 // 'win.autostart'
	// onLogin() authenticated successfully but persisting the activation key to disk failed.
	EventWinKeySaveFailed Event = 95 // 'win.key_save_failed'
	// One stage of managing the ShortNerdCat outbound-allow Windows Firewall rule.
	EventWinFirewall Event = 96 // 'win.firewall'
	// onConnect() began -- state of the existing dialer/tray before any (re-)auth.
	EventWinConnectStart Event = 97 // 'win.connect_start'
	// One stage of re-authenticating a saved key at connect time (dialer was nil).
	EventWinConnectReauth Event = 98 // 'win.connect_reauth'
	// One stage of the DHT UDP-relay bootstrap fallback, tried after direct TCP re-auth fails.
	EventWinConnectUdpRelay Event = 99 // 'win.connect_udp_relay'
	// The forced (--controls) control-node list was registered for this connect.
	EventWinConnectControls Event = 100 // 'win.connect_controls'
	// One stage of the relay-list fetch, data-plane probing, and path building.
	EventWinConnectRelays Event = 102 // 'win.connect_relays'
	// The router found a significantly better control than the one currently in use and switched (token migrated, no re-login).
	EventWinConnectSwitch Event = 103 // 'win.connect_switch'
	// The DHT node was (re)bootstrapped with this connect's control/relay seeds.
	EventWinDhtBootstrap Event = 104 // 'win.dht_bootstrap'
	// One stage of announcing this node as a DHT relay (external-endpoint probe, sign, publish).
	EventWinDhtAnnounce Event = 105 // 'win.dht_announce'
	// One stage of punching to a DHT-discovered relay on behalf of a currently-unreachable control.
	EventWinRelayClient Event = 106 // 'win.relay_client'
	// FetchMyIP's outcome, used both for X-Client-IP stamping and CIDR country pre-detection.
	EventWinMyip Event = 107 // 'win.myip'
	// BypassManager construction failed -- CIDR-based country pre-detection is skipped for this connect.
	EventWinBypassInit Event = 108 // 'win.bypass_init'
	// One stage of CIDR-based country pre-detection, run before the TUN starts.
	EventWinCountryPredetect Event = 109 // 'win.country_predetect'
	// onConnect's routing choice for the router's primary path.
	EventWinPathPick Event = 110 // 'win.path_pick'
	// Decision on whether to upgrade the primary control's dialer to UDP after detecting its TCP path is blocked.
	EventWinUdpUpgrade Event = 111 // 'win.udp_upgrade'
	// A candidate control failed its e2e/UDP viability probe while building the dialer pool -- excluded, exit unreachable.
	EventWinPoolProbeFailed Event = 112 // 'win.pool_probe_failed'
	// One stage of building the connect-time dialer pool (viability topup, per-control auth/dial, final size).
	EventWinPoolBuild Event = 113 // 'win.pool_build'
	// One stage of the live tunnel's own re-auth health (separate from the initial connect-time auth in win.auth).
	EventWinTunnelReauth Event = 114 // 'win.tunnel_reauth'
	// A pool dialer was evicted (or an eviction was skipped/escalated) in response to a failure hook.
	EventWinTunnelEvict Event = 115 // 'win.tunnel_evict'
	// One stage of rebuilding the dialer pool without restarting TUN/routes/DoH, after an eviction.
	EventWinTunnelSilentRefresh Event = 116 // 'win.tunnel_silent_refresh'
	// One stage of standard-mode SOCKS5 listener / TUN adapter / route bring-up.
	EventWinSocks5TunSetup Event = 118 // 'win.socks5_tun_setup'
	// One stage of configuring DNS-over-HTTPS, either at connect time or via the user's tray toggle.
	EventWinDoh Event = 119 // 'win.doh'
	// Final SOCKS5-server stage of onConnect (QUIC blocking, realtime UDP trial dialer, server start).
	EventWinConnectFinalize Event = 120 // 'win.connect_finalize'
	// One stage of the periodic (below-target) dialer pool refill.
	EventWinPoolRefill Event = 121 // 'win.pool_refill'
	// The data-plane watchdog found no traffic for longer than its stale threshold and forced a silent refresh.
	EventWinTunnelWatchdogStale Event = 122 // 'win.tunnel_watchdog_stale'
	// One stage of the live-session periodic country re-check.
	EventWinCountryChange Event = 123 // 'win.country_change'
	// One stage of tearing down the active connection.
	EventWinDisconnect Event = 124 // 'win.disconnect'
	// The system tray (TrayApp) is being created -- blocks until Quit.
	EventWinTrayStart Event = 125 // 'win.tray_start'
	// The user changed a tray setting.
	EventWinSettingsChange Event = 126 // 'win.settings_change'
	// A clean shutdown was signaled (systray Quit or Windows session end).
	EventWinShutdownSignaled Event = 127 // 'win.shutdown_signaled'
	// Persisting a small piece of local state to disk failed.
	EventWinPersistFailed Event = 128 // 'win.persist_failed'
	// One stage of ensureSingleInstance's mutex-takeover sequence when another instance was already running.
	EventWinSingleInstance Event = 129 // 'win.single_instance'
	// detectDeviceCC found a country code from one of its ordered sources.
	EventWinGeoDetect Event = 130 // 'win.geo_detect'
	// CreateWindowExW failed for a native UI window.
	EventWinWindowCreateFailed Event = 131 // 'win.window_create_failed'
	// One stage of the watchdog process restoring networking state after main crashed.
	EventWinWatchdogCleanup Event = 132 // 'win.watchdog_cleanup'
	// One stage of the Windows sleep/hibernate/wake event watcher.
	EventWinPower Event = 133 // 'win.power'
	// One stage of the standalone WebView2 browser window's lifecycle.
	EventWinBrowserWindow Event = 135 // 'win.browser_window'
	// One stage of configuring, cleaning up, or removing DoH/TUN DNS settings.
	EventWinDnsConfig Event = 136 // 'win.dns_config'
	// One stage of the local DoH fallback proxy's lifecycle or per-query handling.
	EventWinDohProxy Event = 137 // 'win.doh_proxy'
	// One stage of the watchdog process's own monitor loop.
	EventWinWatchdogProcess Event = 138 // 'win.watchdog_process'
	// One stage of the watchdog's periodic international-site connectivity probe.
	EventWinWatchdogProbe Event = 139 // 'win.watchdog_probe'
	// One stage of the watchdog obtaining or restarting a handle to the main process.
	EventWinWatchdogMainAttach Event = 140 // 'win.watchdog_main_attach'
	// One stage of snc-core-proxy's bootstrap, run, or shutdown.
	EventWinCoreProxy Event = 141 // 'win.core_proxy'
	// One stage of setWindowIconFromICO.
	EventWinSetIcon Event = 142 // 'win.set_icon'
	// One stage of subclassing the tray window to catch left-clicks.
	EventWinTrayLclickInstall Event = 143 // 'win.tray_lclick_install'
	// One stage of the splash screen's decode/render/show/message-loop sequence.
	EventWinSplash Event = 144 // 'win.splash'
	// One stage of RouteManager applying, extending, or tearing down split-tunnel routes.
	EventWinRoutes Event = 145 // 'win.routes'
	// The user (or an internal channel) triggered a tray menu action.
	EventWinTrayMenuAction Event = 146 // 'win.tray_menu_action'
	// One stage of the tray's connect flow (doConnect).
	EventWinTrayConnect Event = 147 // 'win.tray_connect'
	// One stage of the tray's disconnect flow (doDisconnect).
	EventWinTrayDisconnect Event = 148 // 'win.tray_disconnect'
	// A tray-level state transition outside the connect/disconnect flows themselves (error state, power-wake handling, quit, status callbacks, watchdog).
	EventWinTrayState Event = 149 // 'win.tray_state'
	// The user clicked a control or menu item in the native app window.
	EventWinUiwindowMenu Event = 150 // 'win.uiwindow_menu'
	// One stage of the native app window's own creation/render/message-loop lifecycle.
	EventWinUiwindowLifecycle Event = 151 // 'win.uiwindow_lifecycle'
	// The Kotlin<->Go IPC channel (sendIpc) has produced zero successful sends for longer than the watchdog threshold, even though the tunnel itself is otherwise up -- confirmed live 2026-08-25 as a distinct failure from the already-fixed startup race (2026-08-11): Go's own log showed the socket bound fine, but no send from Kotlin ever landed for the rest of the session. Killing and relaunching the process (fresh generation, fresh socket name) is the only thing that's recovered it in practice. Emitted right before coreProcess.destroy() is called.
	EventAndroidIpcWatchdogRestart Event = 152 // 'android.ipc_watchdog_restart'
	// One stage of an Authenticator login HTTP round trip (doPasswordAuth/ doKeyAuth), via net/http/httptrace -- added 2026-08-27 to pin down exactly where a login hangs (DNS? TCP connect? TLS handshake? sent but no response?) instead of only ever seeing the final "context deadline exceeded" after the full 30s client timeout, which by itself doesn't say which stage never completed. First need: Cat Space's login timing out only while a second, independent VPN (SNC's own) was also active on the same device -- double-tunneled traffic behaves differently at some stage not yet identified.
	EventAuthLoginStage Event = 153 // 'auth.login_stage'
	// The user clicked a button (or otherwise made a choice) in one of the Windows client's native modal dialogs -- ShowKeyDialog, ShowLoginDialog, ShowHaveKeyPrompt, ShowUpdateAvailableDialog (see dialog.go/dialog_auth.go). Added 2026-08-27 alongside win.tray_menu_action and win.uiwindow_menu to close the remaining gap in exhaustive user-action logging -- these three files were the only major Windows UI surfaces with zero logging of user interactions.
	EventWinDialogAction Event = 154 // 'win.dialog_action'
	// The user triggered a tray menu or native NSMenu-bar action on the macOS client (tray_darwin.go) -- added 2026-08-27 alongside the Windows/Linux/Android equivalents to close a total gap (this file had zero logevent.Emit calls despite ~1490 lines and being the main interaction surface). Tray and menu-bar items trigger identical business logic for the same action, so they share one action vocabulary; source distinguishes which physical control was used.
	EventMacTrayAction Event = 155 // 'mac.tray_action'
	// The user made a choice in one of the macOS client's native Cocoa panels (window_cocoa.m via window_cgo_darwin.go's go_snc_* exports), the WebView app-window's settings/recommend/club-theme controls, an osascript-based alert (alert_darwin.go), the legacy osascript key dialog (main_darwin.go). Added 2026-08-27 alongside mac.tray_action.
	EventMacDialogAction Event = 156 // 'mac.dialog_action'
	// The user triggered a tray menu action on the Linux client (tray_linux.go) -- added 2026-08-27 alongside the Windows/Mac/Android equivalents to close a total gap (this file had zero logevent.Emit calls despite ~1147 lines and being the main interaction surface).
	EventLinuxTrayAction Event = 157 // 'linux.tray_action'
	// The user made a choice in the Linux client's GTK/WebKit app window (app_window_linux.go's goAppWinXxx CGo receivers). Added 2026-08-27 alongside linux.tray_action.
	EventLinuxDialogAction Event = 158 // 'linux.dialog_action'
	// The user tapped a button, menu item, checkbox, or dialog choice somewhere in the Android client's UI. Added 2026-08-27 to close a near-total gap: of ~38 distinct tappable controls found across MainActivity, ConnectionFragment, AppsFragment, AppListAdapter, BrowseFragment and BatteryOptimization, only the Connect/Disconnect button had any adjacent LogEvent.emitSystem call before this.
	EventAndroidUiAction Event = 159 // 'android.ui_action'
	// The user tapped a button, menu item, or dialog choice somewhere in the iOS client's UI. Added 2026-08-28, migrating the plain free-text SLog("user: ...") call sites added a session earlier (2026-08-27, before LogEvent.swift/typedEncode existed on this platform) to structured, type-encoded events -- see LogEvent.swift's doc comment for why leaving those as free text would have made the whole structured-logging migration on iOS pointless (the point was compactness + partial obfuscation, which plain text call sites don't get just because the *capability* to emit structured events exists elsewhere in the same binary).
	EventIosUiAction Event = 160 // 'ios.ui_action'
)

// EventNames maps every known event id to its dotted schema name, for
// tooling and for WriteStructuredEvent's own log-on-emit diagnostics.
var EventNames = map[Event]string{
	EventBypassDecision:               "bypass.decision",
	EventTunnelDialStart:              "tunnel.dial_start",
	EventUdpAssocRoutingDecision:      "udp_assoc.routing_decision",
	EventTunnelPostResult:             "tunnel.post_result",
	EventTunnelDialRetry:              "tunnel.dial_retry",
	EventTunnelDialEstablished:        "tunnel.dial_established",
	EventSessionStreamOpened:          "session.stream_opened",
	EventSessionStreamOpenError:       "session.stream_open_error",
	EventSessionStreamGiveup404:       "session.stream_giveup_404",
	EventSessionStreamGiveup:          "session.stream_giveup",
	EventSessionStreamRenewed:         "session.stream_renewed",
	EventSessionStreamFlapped:         "session.stream_flapped",
	EventSessionStreamClosedReopening: "session.stream_closed_reopening",
	EventRouterControlMarkedDead:      "router.control_marked_dead",
	EventRouterUdpDowngraded:          "router.udp_downgraded",
	EventRouterPathsBuilt:             "router.paths_built",
	EventRouterPathEntry:              "router.path_entry",
	EventUdpAssocFallbackToTunnel:     "udp_assoc.fallback_to_tunnel",
	EventUdpAssocPinnedDialer:         "udp_assoc.pinned_dialer",
	EventProtectReconnecting:          "protect.reconnecting",
	EventProtectReconnected:           "protect.reconnected",
	EventProtectWatchdogHung:          "protect.watchdog_hung",
	EventProtectNoSocket:              "protect.no_socket",
	EventProtectIoError:               "protect.io_error",
	EventProtectReconnectAfterError:   "protect.reconnect_after_error",
	EventProtectNack:                  "protect.nack",
	EventProtectOk:                    "protect.ok",
	EventAndroidVpnCreated:            "android.vpn_created",
	EventAndroidVpnStartCommand:       "android.vpn_start_command",
	EventAndroidVpnStartBegin:         "android.vpn_start_begin",
	EventAndroidVpnTunEstablished:     "android.vpn_tun_established",
	EventAndroidVpnStartFailed:        "android.vpn_start_failed",
	EventAndroidVpnProcessExited:      "android.vpn_process_exited",
	EventAndroidVpnStartException:     "android.vpn_start_exception",
	EventAndroidVpnStop:               "android.vpn_stop",
	EventAndroidVpnRevoke:             "android.vpn_revoke",
	EventAndroidVpnDestroyed:          "android.vpn_destroyed",
	EventUpdateCheckerStarted:         "update.checker_started",
	EventUpdateCheckError:             "update.check_error",
	EventUpdateCheckSkipped:           "update.check_skipped",
	EventUpdateCheckStart:             "update.check_start",
	EventUpdateFetchFailed:            "update.fetch_failed",
	EventUpdateInvalidVersion:         "update.invalid_version",
	EventUpdateUpToDate:               "update.up_to_date",
	EventUpdateAvailable:              "update.available",
	EventUpdateDownloadFailed:         "update.download_failed",
	EventUpdateReady:                  "update.ready",
	EventUpdateNoValidVersion:         "update.no_valid_version",
	EventUpdateDirectAttemptFailed:    "update.direct_attempt_failed",
	EventUpdateHttpFailed:             "update.http_failed",
	EventBrowseWebviewInfo:            "browse.webview_info",
	EventBrowsePermissionDenied:       "browse.permission_denied",
	EventBrowseNonHttpScheme:          "browse.non_http_scheme",
	EventBrowseLoadError:              "browse.load_error",
	EventBrowseSslError:               "browse.ssl_error",
	EventUiButtonPressed:              "ui.button_pressed",
	EventAndroidBgServiceLifecycle:    "android.bg_service_lifecycle",
	EventAndroidBatteryExemptionCheck: "android.battery_exemption_check",
	EventAndroidVpnEstablishDiag:      "android.vpn_establish_diag",
	EventAndroidVpnReconnectDecision:  "android.vpn_reconnect_decision",
	EventAndroidProtectLoopError:      "android.protect_loop_error",
	EventAndroidUidLoopError:          "android.uid_loop_error",
	EventAndroidNetworkEvent:          "android.network_event",
	EventAndroidNetworkHeartbeat:      "android.network_heartbeat",
	EventAndroidStateWatchError:       "android.state_watch_error",
	EventAndroidIpcSend:               "android.ipc_send",
	EventWinStartupDiag:               "win.startup_diag",
	EventWinWatchdogLifecycle:         "win.watchdog_lifecycle",
	EventWinPickServerUrl:             "win.pick_server_url",
	EventWinDiscovery:                 "win.discovery",
	EventWinNotification:              "win.notification",
	EventWinClubDiscovery:             "win.club_discovery",
	EventWinClubRecommend:             "win.club_recommend",
	EventWinDhtGossipRejected:         "win.dht_gossip_rejected",
	EventWinMirror:                    "win.mirror",
	EventWinDeepLink:                  "win.deep_link",
	EventWinAuth:                      "win.auth",
	EventWinDeviceId:                  "win.device_id",
	EventWinNodeId:                    "win.node_id",
	EventWinDht:                       "win.dht",
	EventWinGeo:                       "win.geo",
	EventWinAutostart:                 "win.autostart",
	EventWinKeySaveFailed:             "win.key_save_failed",
	EventWinFirewall:                  "win.firewall",
	EventWinConnectStart:              "win.connect_start",
	EventWinConnectReauth:             "win.connect_reauth",
	EventWinConnectUdpRelay:           "win.connect_udp_relay",
	EventWinConnectControls:           "win.connect_controls",
	EventWinConnectRelays:             "win.connect_relays",
	EventWinConnectSwitch:             "win.connect_switch",
	EventWinDhtBootstrap:              "win.dht_bootstrap",
	EventWinDhtAnnounce:               "win.dht_announce",
	EventWinRelayClient:               "win.relay_client",
	EventWinMyip:                      "win.myip",
	EventWinBypassInit:                "win.bypass_init",
	EventWinCountryPredetect:          "win.country_predetect",
	EventWinPathPick:                  "win.path_pick",
	EventWinUdpUpgrade:                "win.udp_upgrade",
	EventWinPoolProbeFailed:           "win.pool_probe_failed",
	EventWinPoolBuild:                 "win.pool_build",
	EventWinTunnelReauth:              "win.tunnel_reauth",
	EventWinTunnelEvict:               "win.tunnel_evict",
	EventWinTunnelSilentRefresh:       "win.tunnel_silent_refresh",
	EventWinSocks5TunSetup:            "win.socks5_tun_setup",
	EventWinDoh:                       "win.doh",
	EventWinConnectFinalize:           "win.connect_finalize",
	EventWinPoolRefill:                "win.pool_refill",
	EventWinTunnelWatchdogStale:       "win.tunnel_watchdog_stale",
	EventWinCountryChange:             "win.country_change",
	EventWinDisconnect:                "win.disconnect",
	EventWinTrayStart:                 "win.tray_start",
	EventWinSettingsChange:            "win.settings_change",
	EventWinShutdownSignaled:          "win.shutdown_signaled",
	EventWinPersistFailed:             "win.persist_failed",
	EventWinSingleInstance:            "win.single_instance",
	EventWinGeoDetect:                 "win.geo_detect",
	EventWinWindowCreateFailed:        "win.window_create_failed",
	EventWinWatchdogCleanup:           "win.watchdog_cleanup",
	EventWinPower:                     "win.power",
	EventWinBrowserWindow:             "win.browser_window",
	EventWinDnsConfig:                 "win.dns_config",
	EventWinDohProxy:                  "win.doh_proxy",
	EventWinWatchdogProcess:           "win.watchdog_process",
	EventWinWatchdogProbe:             "win.watchdog_probe",
	EventWinWatchdogMainAttach:        "win.watchdog_main_attach",
	EventWinCoreProxy:                 "win.core_proxy",
	EventWinSetIcon:                   "win.set_icon",
	EventWinTrayLclickInstall:         "win.tray_lclick_install",
	EventWinSplash:                    "win.splash",
	EventWinRoutes:                    "win.routes",
	EventWinTrayMenuAction:            "win.tray_menu_action",
	EventWinTrayConnect:               "win.tray_connect",
	EventWinTrayDisconnect:            "win.tray_disconnect",
	EventWinTrayState:                 "win.tray_state",
	EventWinUiwindowMenu:              "win.uiwindow_menu",
	EventWinUiwindowLifecycle:         "win.uiwindow_lifecycle",
	EventAndroidIpcWatchdogRestart:    "android.ipc_watchdog_restart",
	EventAuthLoginStage:               "auth.login_stage",
	EventWinDialogAction:              "win.dialog_action",
	EventMacTrayAction:                "mac.tray_action",
	EventMacDialogAction:              "mac.dialog_action",
	EventLinuxTrayAction:              "linux.tray_action",
	EventLinuxDialogAction:            "linux.dialog_action",
	EventAndroidUiAction:              "android.ui_action",
	EventIosUiAction:                  "ios.ui_action",
}

// Attribute key constants -- the CBOR map key strings each event's known
// fields use. A call site MAY use additional keys not listed here (see
// events.yaml's doc comment on `fields` not being an enforced whitelist).
const (
	AttrAddr             = "addr"
	AttrResult           = "result"
	AttrReason           = "reason"
	AttrTarget           = "target"
	AttrConnId           = "conn_id"
	AttrDst              = "dst"
	AttrIsBypassDst      = "is_bypass_dst"
	AttrTunnelOnly       = "tunnel_only"
	AttrControl          = "control"
	AttrReqSeq           = "req_seq"
	AttrPayloadBytes     = "payload_bytes"
	AttrAttempt          = "attempt"
	AttrInitialRespBytes = "initial_resp_bytes"
	AttrCloseReason      = "close_reason"
	AttrCount            = "count"
	AttrMax              = "max"
	AttrUntil            = "until"
	AttrBestMs           = "best_ms"
	AttrIndex            = "index"
	AttrScore            = "score"
	AttrHops             = "hops"
	AttrVia              = "via"
	AttrKey              = "key"
	AttrSentCount        = "sent_count"
	AttrSocketPath       = "socket_path"
	AttrElapsedMs        = "elapsed_ms"
	AttrFd               = "fd"
	AttrStage            = "stage"
	AttrAckByte          = "ack_byte"
	AttrAction           = "action"
	AttrGen              = "gen"
	AttrAttempts         = "attempts"
	AttrPrepareNeeded    = "prepare_needed"
	AttrOtherVpnActive   = "other_vpn_active"
	AttrExitCode         = "exit_code"
	AttrExitState        = "exit_state"
	AttrKeyDenied        = "key_denied"
	AttrIntentional      = "intentional"
	AttrFatal            = "fatal"
	AttrMsg              = "msg"
	AttrSelfStop         = "self_stop"
	AttrHadKey           = "had_key"
	AttrErr              = "err"
	AttrVpnActive        = "vpn_active"
	AttrControlCount     = "control_count"
	AttrCurrentVersion   = "current_version"
	AttrVersion          = "version"
	AttrRemoteVersion    = "remote_version"
	AttrHost             = "host"
	AttrPort             = "port"
	AttrPath             = "path"
	AttrOk               = "ok"
	AttrPkg              = "pkg"
	AttrVersionName      = "version_name"
	AttrAndroidSdk       = "android_sdk"
	AttrAndroidRelease   = "android_release"
	AttrDevice           = "device"
	AttrOrigin           = "origin"
	AttrResources        = "resources"
	AttrScheme           = "scheme"
	AttrUrl              = "url"
	AttrCode             = "code"
	AttrDesc             = "desc"
	AttrPrimaryError     = "primary_error"
	AttrIssuedTo         = "issued_to"
	AttrIssuedBy         = "issued_by"
	AttrValidFrom        = "valid_from"
	AttrValidTo          = "valid_to"
	AttrButton           = "button"
	AttrSource           = "source"
	AttrExempt           = "exempt"
	AttrDelayMs          = "delay_ms"
	AttrOtherVpnInfo     = "other_vpn_info"
	AttrShouldReconnect  = "should_reconnect"
	AttrProcessExited    = "process_exited"
	AttrKeyInvalid       = "key_invalid"
	AttrKind             = "kind"
	AttrDetail           = "detail"
	AttrIpcTag           = "ipc_tag"
	AttrPid              = "pid"
	AttrCc               = "cc"
	AttrControls         = "controls"
	AttrNotifId          = "notif_id"
	AttrCreatedAt        = "created_at"
	AttrSeen             = "seen"
	AttrAgeSec           = "age_sec"
	AttrSlug             = "slug"
	AttrUsername         = "username"
	AttrPeer             = "peer"
	AttrDataDir          = "data_dir"
	AttrFlow             = "flow"
	AttrUser             = "user"
	AttrRelayCc          = "relay_cc"
	AttrValue            = "value"
	AttrNodeId           = "node_id"
	AttrControlUrl       = "control_url"
	AttrRegion           = "region"
	AttrExe              = "exe"
	AttrDialerPresent    = "dialer_present"
	AttrTrayPresent      = "tray_present"
	AttrRelayAddr        = "relay_addr"
	AttrCtrl             = "ctrl"
	AttrList             = "list"
	AttrFrom             = "from"
	AttrTo               = "to"
	AttrCtrlCount        = "ctrl_count"
	AttrRelayCount       = "relay_count"
	AttrGpsDetected      = "gps_detected"
	AttrNeed             = "need"
	AttrTotal            = "total"
	AttrPoolSize         = "pool_size"
	AttrRetryDelayMs     = "retry_delay_ms"
	AttrTrigger          = "trigger"
	AttrSize             = "size"
	AttrIdleMs           = "idle_ms"
	AttrSetting          = "setting"
	AttrWhat             = "what"
	AttrWindow           = "window"
	AttrOrigGw           = "orig_gw"
	AttrSrc              = "src"
	AttrQueryBytes       = "query_bytes"
	AttrRespBytes        = "resp_bytes"
	AttrRound            = "round"
	AttrSilentForMs      = "silent_for_ms"
)

// BypassDecisionReason is bypass.decision's closed vocabulary for the 'reason' field.
const (
	BypassDecisionReasonDisabled          = "disabled"
	BypassDecisionReasonLookupFailed      = "lookup_failed"
	BypassDecisionReasonInvalidResolvedIp = "invalid_resolved_ip"
	BypassDecisionReasonCooldown          = "cooldown"
	BypassDecisionReasonTldOverride       = "tld_override"
	BypassDecisionReasonCidrMembership    = "cidr_membership"
	BypassDecisionReasonNoCidrSet         = "no_cidr_set"
)

// TunnelPostResultResult is tunnel.post_result's closed vocabulary for the 'result' field.
const (
	TunnelPostResultResultOk    = "ok"
	TunnelPostResultResultError = "error"
)

// ProtectIoErrorStage is protect.io_error's closed vocabulary for the 'stage' field.
const (
	ProtectIoErrorStageSend = "send"
	ProtectIoErrorStageAck  = "ack"
)

// ProtectReconnectAfterErrorStage is protect.reconnect_after_error's closed vocabulary for the 'stage' field.
const (
	ProtectReconnectAfterErrorStageSend = "send"
	ProtectReconnectAfterErrorStageAck  = "ack"
)

// ProtectReconnectAfterErrorResult is protect.reconnect_after_error's closed vocabulary for the 'result' field.
const (
	ProtectReconnectAfterErrorResultOk    = "ok"
	ProtectReconnectAfterErrorResultError = "error"
)

// AndroidVpnStartCommandAction is android.vpn_start_command's closed vocabulary for the 'action' field.
const (
	AndroidVpnStartCommandActionStop  = "stop"
	AndroidVpnStartCommandActionStart = "start"
)

// UpdateCheckSkippedReason is update.check_skipped's closed vocabulary for the 'reason' field.
const (
	UpdateCheckSkippedReasonNoControls = "no_controls"
)

// UpdateHttpFailedStage is update.http_failed's closed vocabulary for the 'stage' field.
const (
	UpdateHttpFailedStageFetch    = "fetch"
	UpdateHttpFailedStageDownload = "download"
)

// UpdateHttpFailedReason is update.http_failed's closed vocabulary for the 'reason' field.
const (
	UpdateHttpFailedReasonProtectRefused = "protect_refused"
	UpdateHttpFailedReasonException      = "exception"
)

// UiButtonPressedButton is ui.button_pressed's closed vocabulary for the 'button' field.
const (
	UiButtonPressedButtonConnect    = "connect"
	UiButtonPressedButtonDisconnect = "disconnect"
)

// AndroidBgServiceLifecycleStage is android.bg_service_lifecycle's closed vocabulary for the 'stage' field.
const (
	AndroidBgServiceLifecycleStageCreated         = "created"
	AndroidBgServiceLifecycleStageDestroyed       = "destroyed"
	AndroidBgServiceLifecycleStagePausedForVpn    = "paused_for_vpn"
	AndroidBgServiceLifecycleStageResumedAfterVpn = "resumed_after_vpn"
)

// AndroidBatteryExemptionCheckSource is android.battery_exemption_check's closed vocabulary for the 'source' field.
const (
	AndroidBatteryExemptionCheckSourceAppOpen           = "app_open"
	AndroidBatteryExemptionCheckSourceConnectTap        = "connect_tap"
	AndroidBatteryExemptionCheckSourceBackgroundService = "background_service"
)

// AndroidVpnEstablishDiagStage is android.vpn_establish_diag's closed vocabulary for the 'stage' field.
const (
	AndroidVpnEstablishDiagStagePrepareNeeded  = "prepare_needed"
	AndroidVpnEstablishDiagStageOtherVpnActive = "other_vpn_active"
	AndroidVpnEstablishDiagStageRetry          = "retry"
)

// AndroidProtectLoopErrorStage is android.protect_loop_error's closed vocabulary for the 'stage' field.
const (
	AndroidProtectLoopErrorStageAcceptRetry   = "accept_retry"
	AndroidProtectLoopErrorStageClientLoopEnd = "client_loop_end"
)

// AndroidUidLoopErrorStage is android.uid_loop_error's closed vocabulary for the 'stage' field.
const (
	AndroidUidLoopErrorStageAcceptRetry   = "accept_retry"
	AndroidUidLoopErrorStageClientLoopEnd = "client_loop_end"
)

// AndroidNetworkEventKind is android.network_event's closed vocabulary for the 'kind' field.
const (
	AndroidNetworkEventKindAvailable                  = "available"
	AndroidNetworkEventKindLost                       = "lost"
	AndroidNetworkEventKindCapabilitiesChanged        = "capabilities_changed"
	AndroidNetworkEventKindCallbackRegistered         = "callback_registered"
	AndroidNetworkEventKindInitialDiag                = "initial_diag"
	AndroidNetworkEventKindCallbackRegistrationFailed = "callback_registration_failed"
)

// AndroidIpcSendStage is android.ipc_send's closed vocabulary for the 'stage' field.
const (
	AndroidIpcSendStageSkippedNoPath      = "skipped_no_path"
	AndroidIpcSendStageRetryOk            = "retry_ok"
	AndroidIpcSendStageFailed             = "failed"
	AndroidIpcSendStageSkippedNoTunnel    = "skipped_no_tunnel"
	AndroidIpcSendStageFailedWithResponse = "failed_with_response"
)

// WinStartupDiagStage is win.startup_diag's closed vocabulary for the 'stage' field.
const (
	WinStartupDiagStageControlsOverride          = "controls_override"
	WinStartupDiagStageSingleInstanceBlocked     = "single_instance_blocked"
	WinStartupDiagStagePanic                     = "panic"
	WinStartupDiagStageSplashShowing             = "splash_showing"
	WinStartupDiagStageSplashDone                = "splash_done"
	WinStartupDiagStageKeyLoadStart              = "key_load_start"
	WinStartupDiagStageUpdateFailed              = "update_failed"
	WinStartupDiagStageAdapterPowerDisableFailed = "adapter_power_disable_failed"
	WinStartupDiagStageAdapterPowerDisabled      = "adapter_power_disabled"
	WinStartupDiagStageAdapterPowerRestored      = "adapter_power_restored"
)

// WinWatchdogLifecycleStage is win.watchdog_lifecycle's closed vocabulary for the 'stage' field.
const (
	WinWatchdogLifecycleStageStateWriteFailed = "state_write_failed"
	WinWatchdogLifecycleStageStartFailed      = "start_failed"
	WinWatchdogLifecycleStageStarted          = "started"
	WinWatchdogLifecycleStageAlreadyRunning   = "already_running"
	WinWatchdogLifecycleStageExitedRestarting = "exited_restarting"
	WinWatchdogLifecycleStageRestartFailed    = "restart_failed"
	WinWatchdogLifecycleStageRestarted        = "restarted"
)

// WinPickServerUrlStage is win.pick_server_url's closed vocabulary for the 'stage' field.
const (
	WinPickServerUrlStageForced     = "forced"
	WinPickServerUrlStageInRegion   = "in_region"
	WinPickServerUrlStageNoInRegion = "no_in_region"
)

// WinDiscoveryStage is win.discovery's closed vocabulary for the 'stage' field.
const (
	WinDiscoveryStageControlListUpdated = "control_list_updated"
	WinDiscoveryStageInitFailed         = "init_failed"
	WinDiscoveryStageNoCachedManifest   = "no_cached_manifest"
)

// WinNotificationStage is win.notification's closed vocabulary for the 'stage' field.
const (
	WinNotificationStageReceived    = "received"
	WinNotificationStageItem        = "item"
	WinNotificationStageItemExpired = "item_expired"
	WinNotificationStageNoneNew     = "none_new"
	WinNotificationStageShowing     = "showing"
)

// WinClubDiscoveryStage is win.club_discovery's closed vocabulary for the 'stage' field.
const (
	WinClubDiscoveryStageControlListUpdated = "control_list_updated"
	WinClubDiscoveryStageInitFailed         = "init_failed"
)

// WinClubRecommendResult is win.club_recommend's closed vocabulary for the 'result' field.
const (
	WinClubRecommendResultOk    = "ok"
	WinClubRecommendResultError = "error"
)

// WinMirrorStage is win.mirror's closed vocabulary for the 'stage' field.
const (
	WinMirrorStageInitFailed        = "init_failed"
	WinMirrorStageInitialized       = "initialized"
	WinMirrorStageServerPunchFailed = "server_punch_failed"
	WinMirrorStageServerServing     = "server_serving"
)

// WinDeepLinkResult is win.deep_link's closed vocabulary for the 'result' field.
const (
	WinDeepLinkResultOk    = "ok"
	WinDeepLinkResultError = "error"
)

// WinAuthFlow is win.auth's closed vocabulary for the 'flow' field.
const (
	WinAuthFlowAuto   = "auto"
	WinAuthFlowManual = "manual"
)

// WinAuthStage is win.auth's closed vocabulary for the 'stage' field.
const (
	WinAuthStageTrying          = "trying"
	WinAuthStageFailed          = "failed"
	WinAuthStageOk              = "ok"
	WinAuthStageRelayTrying     = "relay_trying"
	WinAuthStageRelayOk         = "relay_ok"
	WinAuthStageAllUnreachable  = "all_unreachable"
	WinAuthStageSavedKeyInvalid = "saved_key_invalid"
	WinAuthStageNoSavedKey      = "no_saved_key"
)

// WinNodeIdStage is win.node_id's closed vocabulary for the 'stage' field.
const (
	WinNodeIdStageLoadFailed = "load_failed"
	WinNodeIdStageLoaded     = "loaded"
)

// WinDhtStage is win.dht's closed vocabulary for the 'stage' field.
const (
	WinDhtStageStarted                = "started"
	WinDhtStageListenFailed           = "listen_failed"
	WinDhtStageBadNodeId              = "bad_node_id"
	WinDhtStageRelayServerPunchFailed = "relay_server_punch_failed"
	WinDhtStageRelayServerServing     = "relay_server_serving"
)

// WinGeoStage is win.geo's closed vocabulary for the 'stage' field.
const (
	WinGeoStagePersistedCountryLoaded = "persisted_country_loaded"
	WinGeoStageExplicitRegionApplied  = "explicit_region_applied"
	WinGeoStageDeviceCountryApplied   = "device_country_applied"
	WinGeoStageDeviceCountryStored    = "device_country_stored"
)

// WinAutostartResult is win.autostart's closed vocabulary for the 'result' field.
const (
	WinAutostartResultOk    = "ok"
	WinAutostartResultError = "error"
)

// WinFirewallStage is win.firewall's closed vocabulary for the 'stage' field.
const (
	WinFirewallStageExePathFailed = "exe_path_failed"
	WinFirewallStageAddFailed     = "add_failed"
	WinFirewallStageAdded         = "added"
	WinFirewallStageDeleteFailed  = "delete_failed"
	WinFirewallStageRemoved       = "removed"
)

// WinConnectReauthStage is win.connect_reauth's closed vocabulary for the 'stage' field.
const (
	WinConnectReauthStageTrying       = "trying"
	WinConnectReauthStageDirectFailed = "direct_failed"
	WinConnectReauthStageOk           = "ok"
)

// WinConnectUdpRelayStage is win.connect_udp_relay's closed vocabulary for the 'stage' field.
const (
	WinConnectUdpRelayStagePunchFailed = "punch_failed"
	WinConnectUdpRelayStageLoginFailed = "login_failed"
	WinConnectUdpRelayStageOk          = "ok"
)

// WinConnectRelaysStage is win.connect_relays's closed vocabulary for the 'stage' field.
const (
	WinConnectRelaysStageFetching         = "fetching"
	WinConnectRelaysStageSaveFailed       = "save_failed"
	WinConnectRelaysStageFetchFailed      = "fetch_failed"
	WinConnectRelaysStageProbingDataPlane = "probing_data_plane"
	WinConnectRelaysStageBuildingPaths    = "building_paths"
)

// WinDhtAnnounceStage is win.dht_announce's closed vocabulary for the 'stage' field.
const (
	WinDhtAnnounceStageProbeFailed     = "probe_failed"
	WinDhtAnnounceStageSignFailed      = "sign_failed"
	WinDhtAnnounceStageEntrySet        = "entry_set"
	WinDhtAnnounceStageAllProbesFailed = "all_probes_failed"
)

// WinRelayClientStage is win.relay_client's closed vocabulary for the 'stage' field.
const (
	WinRelayClientStagePunching    = "punching"
	WinRelayClientStagePunchFailed = "punch_failed"
	WinRelayClientStageEstablished = "established"
)

// WinMyipResult is win.myip's closed vocabulary for the 'result' field.
const (
	WinMyipResultOk    = "ok"
	WinMyipResultError = "error"
)

// WinCountryPredetectStage is win.country_predetect's closed vocabulary for the 'stage' field.
const (
	WinCountryPredetectStageSkipped   = "skipped"
	WinCountryPredetectStageWaiting   = "waiting"
	WinCountryPredetectStageDetected  = "detected"
	WinCountryPredetectStageSwitching = "switching"
	WinCountryPredetectStageTimedOut  = "timed_out"
)

// WinPathPickStage is win.path_pick's closed vocabulary for the 'stage' field.
const (
	WinPathPickStageUdpRelay = "udp_relay"
	WinPathPickStageTcpRelay = "tcp_relay"
	WinPathPickStageNone     = "none"
)

// WinUdpUpgradeStage is win.udp_upgrade's closed vocabulary for the 'stage' field.
const (
	WinUdpUpgradeStageSkippedTcpAvailable = "skipped_tcp_available"
	WinUdpUpgradeStageUpgraded            = "upgraded"
)

// WinPoolBuildStage is win.pool_build's closed vocabulary for the 'stage' field.
const (
	WinPoolBuildStageTopupNeeded   = "topup_needed"
	WinPoolBuildStageTopupAdded    = "topup_added"
	WinPoolBuildStageAuthFailed    = "auth_failed"
	WinPoolBuildStageDialerFailed  = "dialer_failed"
	WinPoolBuildStageControlAdded  = "control_added"
	WinPoolBuildStageBuilding      = "building"
	WinPoolBuildStagePoolSize      = "pool_size"
	WinPoolBuildStagePoolReady     = "pool_ready"
	WinPoolBuildStageHooksAttached = "hooks_attached"
)

// WinTunnelReauthStage is win.tunnel_reauth's closed vocabulary for the 'stage' field.
const (
	WinTunnelReauthStageWarning                    = "warning"
	WinTunnelReauthStageRecovered                  = "recovered"
	WinTunnelReauthStageFatal                      = "fatal"
	WinTunnelReauthStageServerUnavailableReconnect = "server_unavailable_reconnect"
	WinTunnelReauthStageCredentialsRejected        = "credentials_rejected"
)

// WinTunnelEvictReason is win.tunnel_evict's closed vocabulary for the 'reason' field.
const (
	WinTunnelEvictReasonFirstFail  = "first_fail"
	WinTunnelEvictReasonDataFail   = "data_fail"
	WinTunnelEvictReasonUdpFail    = "udp_fail"
	WinTunnelEvictReasonAuthFail   = "auth_fail"
	WinTunnelEvictReasonPoolEmpty  = "pool_empty"
	WinTunnelEvictReasonLastDialer = "last_dialer"
)

// WinTunnelSilentRefreshStage is win.tunnel_silent_refresh's closed vocabulary for the 'stage' field.
const (
	WinTunnelSilentRefreshStageStarted       = "started"
	WinTunnelSilentRefreshStageDialerFailed  = "dialer_failed"
	WinTunnelSilentRefreshStageSucceeded     = "succeeded"
	WinTunnelSilentRefreshStageAttemptFailed = "attempt_failed"
	WinTunnelSilentRefreshStageTimedOut      = "timed_out"
)

// WinSocks5TunSetupStage is win.socks5_tun_setup's closed vocabulary for the 'stage' field.
const (
	WinSocks5TunSetupStageSocks5Starting      = "socks5_starting"
	WinSocks5TunSetupStageSocks5Listening     = "socks5_listening"
	WinSocks5TunSetupStageTunStarting         = "tun_starting"
	WinSocks5TunSetupStageTunFailed           = "tun_failed"
	WinSocks5TunSetupStageRoutesApplying      = "routes_applying"
	WinSocks5TunSetupStageRoutesFailed        = "routes_failed"
	WinSocks5TunSetupStageConnected           = "connected"
	WinSocks5TunSetupStageDnsPinFailed        = "dns_pin_failed"
	WinSocks5TunSetupStageWatchdogWriteFailed = "watchdog_write_failed"
)

// WinDohTrigger is win.doh's closed vocabulary for the 'trigger' field.
const (
	WinDohTriggerConnect = "connect"
	WinDohTriggerToggle  = "toggle"
)

// WinDohStage is win.doh's closed vocabulary for the 'stage' field.
const (
	WinDohStageConfiguring      = "configuring"
	WinDohStageNetshUnavailable = "netsh_unavailable"
	WinDohStageProxyFailed      = "proxy_failed"
	WinDohStageNetshActive      = "netsh_active"
	WinDohStageDisabled         = "disabled"
)

// WinConnectFinalizeStage is win.connect_finalize's closed vocabulary for the 'stage' field.
const (
	WinConnectFinalizeStageStartingServer         = "starting_server"
	WinConnectFinalizeStageQuicBlocked            = "quic_blocked"
	WinConnectFinalizeStageRealtimeUdpReady       = "realtime_udp_ready"
	WinConnectFinalizeStageRealtimeUdpUnavailable = "realtime_udp_unavailable"
	WinConnectFinalizeStageServerStarted          = "server_started"
)

// WinPoolRefillStage is win.pool_refill's closed vocabulary for the 'stage' field.
const (
	WinPoolRefillStageBelowTarget  = "below_target"
	WinPoolRefillStageAuthFailed   = "auth_failed"
	WinPoolRefillStageDialerFailed = "dialer_failed"
)

// WinCountryChangeStage is win.country_change's closed vocabulary for the 'stage' field.
const (
	WinCountryChangeStageChanged                = "changed"
	WinCountryChangeStageRegionSet              = "region_set"
	WinCountryChangeStagePoolCompleteAfterRetry = "pool_complete_after_retry"
	WinCountryChangeStageCidrInitSkipped        = "cidr_init_skipped"
)

// WinDisconnectStage is win.disconnect's closed vocabulary for the 'stage' field.
const (
	WinDisconnectStageAutoReconnect       = "auto_reconnect"
	WinDisconnectStageUserInitiated       = "user_initiated"
	WinDisconnectStageWatchdogWriteFailed = "watchdog_write_failed"
	WinDisconnectStageDisconnected        = "disconnected"
)

// WinSettingsChangeSetting is win.settings_change's closed vocabulary for the 'setting' field.
const (
	WinSettingsChangeSettingBlockQuic = "block_quic"
	WinSettingsChangeSettingRegion    = "region"
)

// WinPersistFailedWhat is win.persist_failed's closed vocabulary for the 'what' field.
const (
	WinPersistFailedWhatDeviceId = "device_id"
	WinPersistFailedWhatCountry  = "country"
)

// WinSingleInstanceStage is win.single_instance's closed vocabulary for the 'stage' field.
const (
	WinSingleInstanceStageTerminatingOther = "terminating_other"
	WinSingleInstanceStageKillFailed       = "kill_failed"
	WinSingleInstanceStageOldTerminated    = "old_terminated"
)

// WinGeoDetectSource is win.geo_detect's closed vocabulary for the 'source' field.
const (
	WinGeoDetectSourceGps          = "gps"
	WinGeoDetectSourceSystemLocale = "system_locale"
	WinGeoDetectSourceTimezone     = "timezone"
)

// WinWindowCreateFailedWindow is win.window_create_failed's closed vocabulary for the 'window' field.
const (
	WinWindowCreateFailedWindowKeyDialog    = "key_dialog"
	WinWindowCreateFailedWindowNotification = "notification"
)

// WinWatchdogCleanupStage is win.watchdog_cleanup's closed vocabulary for the 'stage' field.
const (
	WinWatchdogCleanupStageRestoring     = "restoring"
	WinWatchdogCleanupStageRoutesRemoved = "routes_removed"
)

// WinPowerStage is win.power's closed vocabulary for the 'stage' field.
const (
	WinPowerStageWake                = "wake"
	WinPowerStageClassRegisterFailed = "class_register_failed"
	WinPowerStageWindowCreateFailed  = "window_create_failed"
	WinPowerStageWatcherStarted      = "watcher_started"
)

// WinBrowserWindowStage is win.browser_window's closed vocabulary for the 'stage' field.
const (
	WinBrowserWindowStagePanic        = "panic"
	WinBrowserWindowStageCreating     = "creating"
	WinBrowserWindowStageInitFailed   = "init_failed"
	WinBrowserWindowStageReady        = "ready"
	WinBrowserWindowStageWndprocPanic = "wndproc_panic"
	WinBrowserWindowStageEnteringRun  = "entering_run"
)

// WinDnsConfigStage is win.dns_config's closed vocabulary for the 'stage' field.
const (
	WinDnsConfigStageDohEnabled         = "doh_enabled"
	WinDnsConfigStageCleanupNoneFound   = "cleanup_none_found"
	WinDnsConfigStageCleanupRemoved     = "cleanup_removed"
	WinDnsConfigStageDohFallbackActive  = "doh_fallback_active"
	WinDnsConfigStageFallbackStopped    = "fallback_stopped"
	WinDnsConfigStageFallbackStopFailed = "fallback_stop_failed"
	WinDnsConfigStageDohRemoved         = "doh_removed"
	WinDnsConfigStageDohRemoveFailed    = "doh_remove_failed"
)

// WinDohProxyStage is win.doh_proxy's closed vocabulary for the 'stage' field.
const (
	WinDohProxyStageListening     = "listening"
	WinDohProxyStageStopped       = "stopped"
	WinDohProxyStageRecvError     = "recv_error"
	WinDohProxyStageForwardFailed = "forward_failed"
	WinDohProxyStageWriteFailed   = "write_failed"
	WinDohProxyStageResolved      = "resolved"
)

// WinWatchdogProcessStage is win.watchdog_process's closed vocabulary for the 'stage' field.
const (
	WinWatchdogProcessStageStarted               = "started"
	WinWatchdogProcessStageEventsCreateFailed    = "events_create_failed"
	WinWatchdogProcessStagePipeUnavailable       = "pipe_unavailable"
	WinWatchdogProcessStageStaleStateCleanup     = "stale_state_cleanup"
	WinWatchdogProcessStageMainHandleFailed      = "main_handle_failed"
	WinWatchdogProcessStageProbeRestart          = "probe_restart"
	WinWatchdogProcessStageCleanShutdownSignaled = "clean_shutdown_signaled"
	WinWatchdogProcessStageCleanShutdownTimeout  = "clean_shutdown_timeout"
	WinWatchdogProcessStageLastaliveStaleWait    = "lastalive_stale_wait"
	WinWatchdogProcessStageLastaliveFrozenKill   = "lastalive_frozen_kill"
	WinWatchdogProcessStagePipeHeartbeatStale    = "pipe_heartbeat_stale"
	WinWatchdogProcessStageMainExited            = "main_exited"
	WinWatchdogProcessStageExitingClean          = "exiting_clean"
	WinWatchdogProcessStageOtaRestart            = "ota_restart"
	WinWatchdogProcessStageCrashCleanup          = "crash_cleanup"
	WinWatchdogProcessStageRestartGiveup         = "restart_giveup"
)

// WinWatchdogProbeStage is win.watchdog_probe's closed vocabulary for the 'stage' field.
const (
	WinWatchdogProbeStageAllUnreachable = "all_unreachable"
	WinWatchdogProbeStageConfirmedDead  = "confirmed_dead"
)

// WinWatchdogMainAttachStage is win.watchdog_main_attach's closed vocabulary for the 'stage' field.
const (
	WinWatchdogMainAttachStageAttachedExisting = "attached_existing"
	WinWatchdogMainAttachStageStartedFresh     = "started_fresh"
	WinWatchdogMainAttachStageStartFailed      = "start_failed"
	WinWatchdogMainAttachStageHandleFailed     = "handle_failed"
	WinWatchdogMainAttachStageAlreadyRunning   = "already_running"
	WinWatchdogMainAttachStageStalePidReused   = "stale_pid_reused"
	WinWatchdogMainAttachStageRestarted        = "restarted"
	WinWatchdogMainAttachStageRestartFailed    = "restart_failed"
)

// WinCoreProxyStage is win.core_proxy's closed vocabulary for the 'stage' field.
const (
	WinCoreProxyStageStarting               = "starting"
	WinCoreProxyStageInvalidKey             = "invalid_key"
	WinCoreProxyStageNoServerAddrs          = "no_server_addrs"
	WinCoreProxyStageAuthFailed             = "auth_failed"
	WinCoreProxyStageAllControlsUnreachable = "all_controls_unreachable"
	WinCoreProxyStageAuthOk                 = "auth_ok"
	WinCoreProxyStageSocks5ListenFailed     = "socks5_listen_failed"
	WinCoreProxyStageSocks5Ready            = "socks5_ready"
	WinCoreProxyStageShuttingDown           = "shutting_down"
	WinCoreProxyStageRecoveryReachable      = "recovery_reachable"
)

// WinSetIconStage is win.set_icon's closed vocabulary for the 'stage' field.
const (
	WinSetIconStageStart   = "start"
	WinSetIconStageCreated = "created"
)

// WinTrayLclickInstallStage is win.tray_lclick_install's closed vocabulary for the 'stage' field.
const (
	WinTrayLclickInstallStageSearching     = "searching"
	WinTrayLclickInstallStageNotFound      = "not_found"
	WinTrayLclickInstallStageFound         = "found"
	WinTrayLclickInstallStagePanic         = "panic"
	WinTrayLclickInstallStageSystrayMsg    = "systray_msg"
	WinTrayLclickInstallStageClickDetected = "click_detected"
	WinTrayLclickInstallStageSubclassed    = "subclassed"
)

// WinSplashStage is win.splash's closed vocabulary for the 'stage' field.
const (
	WinSplashStageStart             = "start"
	WinSplashStageDecodeFailed      = "decode_failed"
	WinSplashStageDecoded           = "decoded"
	WinSplashStageDibFailed         = "dib_failed"
	WinSplashStageDibCreated        = "dib_created"
	WinSplashStageWindowFailed      = "window_failed"
	WinSplashStageWindowCreated     = "window_created"
	WinSplashStageUpdateLayered     = "update_layered"
	WinSplashStageShown             = "shown"
	WinSplashStageTimerSet          = "timer_set"
	WinSplashStageQuit              = "quit"
	WinSplashStageDismissedTimer    = "dismissed_timer"
	WinSplashStageDismissedClick    = "dismissed_click"
	WinSplashStageDone              = "done"
	WinSplashStageFontBoldFailed    = "font_bold_failed"
	WinSplashStageFontRegularFailed = "font_regular_failed"
	WinSplashStageTitleFaceFailed   = "title_face_failed"
	WinSplashStageVersionFaceFailed = "version_face_failed"
)

// WinRoutesStage is win.routes's closed vocabulary for the 'stage' field.
const (
	WinRoutesStageServerResolved       = "server_resolved"
	WinRoutesStageGatewayFound         = "gateway_found"
	WinRoutesStageLocalIpFound         = "local_ip_found"
	WinRoutesStageLocalIpFailed        = "local_ip_failed"
	WinRoutesStageServerBypassAdded    = "server_bypass_added"
	WinRoutesStageServerBypassFailed   = "server_bypass_failed"
	WinRoutesStageTunIfaceFound        = "tun_iface_found"
	WinRoutesStageSplitRouteAdded      = "split_route_added"
	WinRoutesStageIpv6DisabledBlocking = "ipv6_disabled_blocking"
	WinRoutesStageIpv6BlockFailed      = "ipv6_block_failed"
	WinRoutesStageIpv6BlockOk          = "ipv6_block_ok"
	WinRoutesStageIpv6RouteAdded       = "ipv6_route_added"
	WinRoutesStageIpv6RouteFailed      = "ipv6_route_failed"
	WinRoutesStageBypassAdded          = "bypass_added"
	WinRoutesStageBypassFailed         = "bypass_failed"
	WinRoutesStageIpv6UnblockFailed    = "ipv6_unblock_failed"
	WinRoutesStageIpv6Unblocked        = "ipv6_unblocked"
)

// WinTrayMenuActionAction is win.tray_menu_action's closed vocabulary for the 'action' field.
const (
	WinTrayMenuActionActionOpenWindow         = "open_window"
	WinTrayMenuActionActionLogin              = "login"
	WinTrayMenuActionActionLogout             = "logout"
	WinTrayMenuActionActionConnect            = "connect"
	WinTrayMenuActionActionDisconnect         = "disconnect"
	WinTrayMenuActionActionDohToggle          = "doh_toggle"
	WinTrayMenuActionActionDohNow             = "doh_now"
	WinTrayMenuActionActionBlockQuicToggle    = "block_quic_toggle"
	WinTrayMenuActionActionBlockQuicNow       = "block_quic_now"
	WinTrayMenuActionActionRegionAuto         = "region_auto"
	WinTrayMenuActionActionRegionRu           = "region_ru"
	WinTrayMenuActionActionRegionEu           = "region_eu"
	WinTrayMenuActionActionRegionUs           = "region_us"
	WinTrayMenuActionActionRegionCn           = "region_cn"
	WinTrayMenuActionActionRegionOther        = "region_other"
	WinTrayMenuActionActionConnectCh          = "connect_ch"
	WinTrayMenuActionActionDisconnectCh       = "disconnect_ch"
	WinTrayMenuActionActionReconnectCh        = "reconnect_ch"
	WinTrayMenuActionActionUpdateNotification = "update_notification"
	WinTrayMenuActionActionUpdateClick        = "update_click"
	WinTrayMenuActionActionLoginCh            = "login_ch"
	WinTrayMenuActionActionLogoutCh           = "logout_ch"
	WinTrayMenuActionActionQuitCh             = "quit_ch"
	WinTrayMenuActionActionAbout              = "about"
	WinTrayMenuActionActionQuit               = "quit"
)

// WinTrayConnectStage is win.tray_connect's closed vocabulary for the 'stage' field.
const (
	WinTrayConnectStageLoginFailed             = "login_failed"
	WinTrayConnectStageAlreadyInProgress       = "already_in_progress"
	WinTrayConnectStageStarting                = "starting"
	WinTrayConnectStageUiHidingConnect         = "ui_hiding_connect"
	WinTrayConnectStagePanic                   = "panic"
	WinTrayConnectStageErrorEntering           = "error_entering"
	WinTrayConnectStageFailed                  = "failed"
	WinTrayConnectStageUiRestoreConnect        = "ui_restore_connect"
	WinTrayConnectStageRequeuePending          = "requeue_pending"
	WinTrayConnectStageDisconnectDuringConnect = "disconnect_during_connect"
	WinTrayConnectStageRequeueAfterDisconnect  = "requeue_after_disconnect"
	WinTrayConnectStageUiPendingRestore        = "ui_pending_restore"
	WinTrayConnectStageSuccess                 = "success"
)

// WinTrayDisconnectStage is win.tray_disconnect's closed vocabulary for the 'stage' field.
const (
	WinTrayDisconnectStageDrainedStale              = "drained_stale"
	WinTrayDisconnectStageStarting                  = "starting"
	WinTrayDisconnectStageNotConnectedPending       = "not_connected_pending"
	WinTrayDisconnectStageConnectingToDisconnecting = "connecting_to_disconnecting"
	WinTrayDisconnectStageHidingActions             = "hiding_actions"
	WinTrayDisconnectStageHungForcingReset          = "hung_forcing_reset"
	WinTrayDisconnectStageDone                      = "done"
	WinTrayDisconnectStageRestoringIdle             = "restoring_idle"
	WinTrayDisconnectStageShowingConnect            = "showing_connect"
)

// WinTrayStateStage is win.tray_state's closed vocabulary for the 'stage' field.
const (
	WinTrayStateStageLoginError               = "login_error"
	WinTrayStateStageReconnectSuppressed      = "reconnect_suppressed"
	WinTrayStateStagePowerWakeDebounced       = "power_wake_debounced"
	WinTrayStateStagePowerWakeHealthySkip     = "power_wake_healthy_skip"
	WinTrayStateStageQuitDisconnectTimeout    = "quit_disconnect_timeout"
	WinTrayStateStageUpdateReset              = "update_reset"
	WinTrayStateStageStatusChange             = "status_change"
	WinTrayStateStageWatchdogStuck            = "watchdog_stuck"
	WinTrayStateStageErrorStateConnectionLost = "error_state_connection_lost"
)

// WinUiwindowMenuAction is win.uiwindow_menu's closed vocabulary for the 'action' field.
const (
	WinUiwindowMenuActionConnect        = "connect"
	WinUiwindowMenuActionDisconnect     = "disconnect"
	WinUiwindowMenuActionCheckboxToggle = "checkbox_toggle"
	WinUiwindowMenuActionRegionCombo    = "region_combo"
	WinUiwindowMenuActionLogin          = "login"
	WinUiwindowMenuActionLogout         = "logout"
	WinUiwindowMenuActionConnectMenu    = "connect_menu"
	WinUiwindowMenuActionDisconnectMenu = "disconnect_menu"
	WinUiwindowMenuActionDohToggle      = "doh_toggle"
	WinUiwindowMenuActionQuicToggle     = "quic_toggle"
	WinUiwindowMenuActionAbout          = "about"
	WinUiwindowMenuActionUpdate         = "update"
	WinUiwindowMenuActionQuit           = "quit"
)

// WinUiwindowLifecycleStage is win.uiwindow_lifecycle's closed vocabulary for the 'stage' field.
const (
	WinUiwindowLifecycleStagePanic             = "panic"
	WinUiwindowLifecycleStageClassIcon         = "class_icon"
	WinUiwindowLifecycleStageStart             = "start"
	WinUiwindowLifecycleStageRunPanic          = "run_panic"
	WinUiwindowLifecycleStageHicon             = "hicon"
	WinUiwindowLifecycleStageWindowFailed      = "window_failed"
	WinUiwindowLifecycleStageHwndCreated       = "hwnd_created"
	WinUiwindowLifecycleStageInitialIcon       = "initial_icon"
	WinUiwindowLifecycleStageReady             = "ready"
	WinUiwindowLifecycleStageMessageLoopExited = "message_loop_exited"
	WinUiwindowLifecycleStageBgDecodeFailed    = "bg_decode_failed"
	WinUiwindowLifecycleStageDibFailed         = "dib_failed"
	WinUiwindowLifecycleStageBgReady           = "bg_ready"
	WinUiwindowLifecycleStageCatDecodeFailed   = "cat_decode_failed"
	WinUiwindowLifecycleStageCatBgDecodeFailed = "cat_bg_decode_failed"
	WinUiwindowLifecycleStageClubTheme         = "club_theme"
	WinUiwindowLifecycleStageStatusDropped     = "status_dropped"
	WinUiwindowLifecycleStageStatus            = "status"
)

// AuthLoginStageStage is auth.login_stage's closed vocabulary for the 'stage' field.
const (
	AuthLoginStageStageDnsStart     = "dns_start"
	AuthLoginStageStageDnsDone      = "dns_done"
	AuthLoginStageStageConnectStart = "connect_start"
	AuthLoginStageStageConnectDone  = "connect_done"
	AuthLoginStageStageTlsStart     = "tls_start"
	AuthLoginStageStageTlsDone      = "tls_done"
	AuthLoginStageStageWroteRequest = "wrote_request"
	AuthLoginStageStageGotFirstByte = "got_first_byte"
	AuthLoginStageStageDone         = "done"
	AuthLoginStageStageError        = "error"
)

// WinDialogActionAction is win.dialog_action's closed vocabulary for the 'action' field.
const (
	WinDialogActionActionKeyDialogScanImage        = "key_dialog_scan_image"
	WinDialogActionActionKeyDialogOk               = "key_dialog_ok"
	WinDialogActionActionKeyDialogOkInvalid        = "key_dialog_ok_invalid"
	WinDialogActionActionKeyDialogCancel           = "key_dialog_cancel"
	WinDialogActionActionKeyDialogLoginInstead     = "key_dialog_login_instead"
	WinDialogActionActionHaveKeyYes                = "have_key_yes"
	WinDialogActionActionHaveKeyNo                 = "have_key_no"
	WinDialogActionActionLoginDialogOk             = "login_dialog_ok"
	WinDialogActionActionLoginDialogOkIncomplete   = "login_dialog_ok_incomplete"
	WinDialogActionActionLoginDialogCancel         = "login_dialog_cancel"
	WinDialogActionActionLoginDialogKeymode        = "login_dialog_keymode"
	WinDialogActionActionLoginDialogPasswordToggle = "login_dialog_password_toggle"
	WinDialogActionActionUpdateDialogYes           = "update_dialog_yes"
	WinDialogActionActionUpdateDialogNo            = "update_dialog_no"
)

// MacTrayActionAction is mac.tray_action's closed vocabulary for the 'action' field.
const (
	MacTrayActionActionOpenWindow      = "open_window"
	MacTrayActionActionLogin           = "login"
	MacTrayActionActionLogout          = "logout"
	MacTrayActionActionConnect         = "connect"
	MacTrayActionActionDisconnect      = "disconnect"
	MacTrayActionActionDohToggle       = "doh_toggle"
	MacTrayActionActionBlockQuicToggle = "block_quic_toggle"
	MacTrayActionActionRegionAuto      = "region_auto"
	MacTrayActionActionRegionRu        = "region_ru"
	MacTrayActionActionRegionEu        = "region_eu"
	MacTrayActionActionRegionUs        = "region_us"
	MacTrayActionActionRegionCn        = "region_cn"
	MacTrayActionActionRegionOther     = "region_other"
	MacTrayActionActionUpdateClick     = "update_click"
	MacTrayActionActionAbout           = "about"
	MacTrayActionActionShareLogs       = "share_logs"
	MacTrayActionActionQuit            = "quit"
)

// MacDialogActionAction is mac.dialog_action's closed vocabulary for the 'action' field.
const (
	MacDialogActionActionKeyDialogConnect          = "key_dialog_connect"
	MacDialogActionActionKeyDialogCancel           = "key_dialog_cancel"
	MacDialogActionActionKeyDialogScanImage        = "key_dialog_scan_image"
	MacDialogActionActionKeyDialogPaste            = "key_dialog_paste"
	MacDialogActionActionHaveKeyYes                = "have_key_yes"
	MacDialogActionActionHaveKeyNo                 = "have_key_no"
	MacDialogActionActionLoginDialogLogin          = "login_dialog_login"
	MacDialogActionActionLoginDialogCancel         = "login_dialog_cancel"
	MacDialogActionActionLoginDialogKeymode        = "login_dialog_keymode"
	MacDialogActionActionLoginDialogPasswordToggle = "login_dialog_password_toggle"
	MacDialogActionActionWindowConnect             = "window_connect"
	MacDialogActionActionWindowDisconnect          = "window_disconnect"
	MacDialogActionActionWindowSettingsChanged     = "window_settings_changed"
	MacDialogActionActionWindowRecommendSubmit     = "window_recommend_submit"
	MacDialogActionActionWindowClubThemePreview    = "window_club_theme_preview"
	MacDialogActionActionUpdateDialogNow           = "update_dialog_now"
	MacDialogActionActionUpdateDialogLater         = "update_dialog_later"
	MacDialogActionActionLegacyKeyDialogOk         = "legacy_key_dialog_ok"
	MacDialogActionActionLegacyKeyDialogCancel     = "legacy_key_dialog_cancel"
)

// LinuxTrayActionAction is linux.tray_action's closed vocabulary for the 'action' field.
const (
	LinuxTrayActionActionLogin           = "login"
	LinuxTrayActionActionLogout          = "logout"
	LinuxTrayActionActionConnect         = "connect"
	LinuxTrayActionActionDisconnect      = "disconnect"
	LinuxTrayActionActionDohToggle       = "doh_toggle"
	LinuxTrayActionActionBlockQuicToggle = "block_quic_toggle"
	LinuxTrayActionActionRegionAuto      = "region_auto"
	LinuxTrayActionActionRegionRu        = "region_ru"
	LinuxTrayActionActionRegionEu        = "region_eu"
	LinuxTrayActionActionRegionUs        = "region_us"
	LinuxTrayActionActionRegionCn        = "region_cn"
	LinuxTrayActionActionRegionOther     = "region_other"
	LinuxTrayActionActionUpdateClick     = "update_click"
	LinuxTrayActionActionOpenWindow      = "open_window"
	LinuxTrayActionActionShareLogs       = "share_logs"
	LinuxTrayActionActionAbout           = "about"
	LinuxTrayActionActionQuit            = "quit"
)

// LinuxDialogActionAction is linux.dialog_action's closed vocabulary for the 'action' field.
const (
	LinuxDialogActionActionHaveKeyYes             = "have_key_yes"
	LinuxDialogActionActionHaveKeyNo              = "have_key_no"
	LinuxDialogActionActionCredentialLogin        = "credential_login"
	LinuxDialogActionActionKeyModeSwitch          = "key_mode_switch"
	LinuxDialogActionActionActivateKey            = "activate_key"
	LinuxDialogActionActionWindowConnect          = "window_connect"
	LinuxDialogActionActionWindowDisconnect       = "window_disconnect"
	LinuxDialogActionActionWindowSettingsChanged  = "window_settings_changed"
	LinuxDialogActionActionWindowClubThemePreview = "window_club_theme_preview"
	LinuxDialogActionActionWindowRecommendSubmit  = "window_recommend_submit"
)

// AndroidUiActionAction is android.ui_action's closed vocabulary for the 'action' field.
const (
	AndroidUiActionActionDisableIpv6Toggle    = "disable_ipv6_toggle"
	AndroidUiActionActionDisableUdpToggle     = "disable_udp_toggle"
	AndroidUiActionActionDisableQuicToggle    = "disable_quic_toggle"
	AndroidUiActionActionDisableBypassToggle  = "disable_bypass_toggle"
	AndroidUiActionActionShareLogs            = "share_logs"
	AndroidUiActionActionUpdateMenuOpen       = "update_menu_open"
	AndroidUiActionActionUpdateDialogInstall  = "update_dialog_install"
	AndroidUiActionActionUpdateDialogLater    = "update_dialog_later"
	AndroidUiActionActionLogoutMenuOpen       = "logout_menu_open"
	AndroidUiActionActionLogoutConfirmRemove  = "logout_confirm_remove"
	AndroidUiActionActionLogoutConfirmCancel  = "logout_confirm_cancel"
	AndroidUiActionActionRecommendMenuOpen    = "recommend_menu_open"
	AndroidUiActionActionRecommendSend        = "recommend_send"
	AndroidUiActionActionRecommendCancel      = "recommend_cancel"
	AndroidUiActionActionClubThemeRegular     = "club_theme_regular"
	AndroidUiActionActionClubThemeCatclub     = "club_theme_catclub"
	AndroidUiActionActionClubThemeElite       = "club_theme_elite"
	AndroidUiActionActionActivateKey          = "activate_key"
	AndroidUiActionActionHaveKeyYes           = "have_key_yes"
	AndroidUiActionActionHaveKeyNo            = "have_key_no"
	AndroidUiActionActionKeyEntryLoginInstead = "key_entry_login_instead"
	AndroidUiActionActionSwitchToKeyEntry     = "switch_to_key_entry"
	AndroidUiActionActionTogglePassword       = "toggle_password"
	AndroidUiActionActionDoLogin              = "do_login"
	AndroidUiActionActionScanQr               = "scan_qr"
	AndroidUiActionActionScanFile             = "scan_file"
	AndroidUiActionActionAppsSelectAll        = "apps_select_all"
	AndroidUiActionActionAppsDeselectAll      = "apps_deselect_all"
	AndroidUiActionActionAppsRowToggle        = "apps_row_toggle"
	AndroidUiActionActionBrowseNavBack        = "browse_nav_back"
	AndroidUiActionActionBrowseNavForward     = "browse_nav_forward"
	AndroidUiActionActionBrowseReload         = "browse_reload"
	AndroidUiActionActionBrowseTabsOpen       = "browse_tabs_open"
	AndroidUiActionActionBrowseTabNew         = "browse_tab_new"
	AndroidUiActionActionBrowseTabClose       = "browse_tab_close"
	AndroidUiActionActionBrowseTabSwitch      = "browse_tab_switch"
	AndroidUiActionActionBrowseRetryPage      = "browse_retry_page"
	AndroidUiActionActionBatteryOptAllow      = "battery_opt_allow"
	AndroidUiActionActionBatteryOptNotNow     = "battery_opt_not_now"
)

// IosUiActionAction is ios.ui_action's closed vocabulary for the 'action' field.
const (
	IosUiActionActionConnect               = "connect"
	IosUiActionActionDisconnect            = "disconnect"
	IosUiActionActionLogoutMenuOpen        = "logout_menu_open"
	IosUiActionActionLogoutConfirmRemove   = "logout_confirm_remove"
	IosUiActionActionLogoutConfirmCancel   = "logout_confirm_cancel"
	IosUiActionActionKeyEntryLoginInstead  = "key_entry_login_instead"
	IosUiActionActionHaveKeyYes            = "have_key_yes"
	IosUiActionActionHaveKeyNo             = "have_key_no"
	IosUiActionActionSwitchToKeyEntry      = "switch_to_key_entry"
	IosUiActionActionTogglePassword        = "toggle_password"
	IosUiActionActionCredentialLoginSubmit = "credential_login_submit"
	IosUiActionActionScanQr                = "scan_qr"
	IosUiActionActionScanFile              = "scan_file"
	IosUiActionActionUpdateBannerTap       = "update_banner_tap"
	IosUiActionActionShareLogs             = "share_logs"
	IosUiActionActionBrowserBack           = "browser_back"
	IosUiActionActionBrowserForward        = "browser_forward"
	IosUiActionActionBrowserReload         = "browser_reload"
	IosUiActionActionBrowserTabsOpen       = "browser_tabs_open"
	IosUiActionActionBrowserTabSwitch      = "browser_tab_switch"
	IosUiActionActionBrowserTabNew         = "browser_tab_new"
	IosUiActionActionBrowserTabClose       = "browser_tab_close"
	IosUiActionActionBrowserUrlSubmit      = "browser_url_submit"
	IosUiActionActionQrScanCancel          = "qr_scan_cancel"
	IosUiActionActionQrCodeScanned         = "qr_code_scanned"
	IosUiActionActionUpdateNotificationTap = "update_notification_tap"
)

// enumFieldValues holds each enum-typed field's declared value list, in
// schema order -- Emit() encodes a matching string as that value's index
// (uint) instead of the literal text; render/decode tooling reverses this.
var enumFieldValues = map[Event]map[string][]string{
	EventBypassDecision: {
		"reason": {"disabled", "lookup_failed", "invalid_resolved_ip", "cooldown", "tld_override", "cidr_membership", "no_cidr_set"},
	},
	EventTunnelPostResult: {
		"result": {"ok", "error"},
	},
	EventProtectIoError: {
		"stage": {"send", "ack"},
	},
	EventProtectReconnectAfterError: {
		"stage":  {"send", "ack"},
		"result": {"ok", "error"},
	},
	EventAndroidVpnStartCommand: {
		"action": {"stop", "start"},
	},
	EventUpdateCheckSkipped: {
		"reason": {"no_controls"},
	},
	EventUpdateHttpFailed: {
		"stage":  {"fetch", "download"},
		"reason": {"protect_refused", "exception"},
	},
	EventUiButtonPressed: {
		"button": {"connect", "disconnect"},
	},
	EventAndroidBgServiceLifecycle: {
		"stage": {"created", "destroyed", "paused_for_vpn", "resumed_after_vpn"},
	},
	EventAndroidBatteryExemptionCheck: {
		"source": {"app_open", "connect_tap", "background_service"},
	},
	EventAndroidVpnEstablishDiag: {
		"stage": {"prepare_needed", "other_vpn_active", "retry"},
	},
	EventAndroidProtectLoopError: {
		"stage": {"accept_retry", "client_loop_end"},
	},
	EventAndroidUidLoopError: {
		"stage": {"accept_retry", "client_loop_end"},
	},
	EventAndroidNetworkEvent: {
		"kind": {"available", "lost", "capabilities_changed", "callback_registered", "initial_diag", "callback_registration_failed"},
	},
	EventAndroidIpcSend: {
		"stage": {"skipped_no_path", "retry_ok", "failed", "skipped_no_tunnel", "failed_with_response"},
	},
	EventWinStartupDiag: {
		"stage": {"controls_override", "single_instance_blocked", "panic", "splash_showing", "splash_done", "key_load_start", "update_failed", "adapter_power_disable_failed", "adapter_power_disabled", "adapter_power_restored"},
	},
	EventWinWatchdogLifecycle: {
		"stage": {"state_write_failed", "start_failed", "started", "already_running", "exited_restarting", "restart_failed", "restarted"},
	},
	EventWinPickServerUrl: {
		"stage": {"forced", "in_region", "no_in_region"},
	},
	EventWinDiscovery: {
		"stage": {"control_list_updated", "init_failed", "no_cached_manifest"},
	},
	EventWinNotification: {
		"stage": {"received", "item", "item_expired", "none_new", "showing"},
	},
	EventWinClubDiscovery: {
		"stage": {"control_list_updated", "init_failed"},
	},
	EventWinClubRecommend: {
		"result": {"ok", "error"},
	},
	EventWinMirror: {
		"stage": {"init_failed", "initialized", "server_punch_failed", "server_serving"},
	},
	EventWinDeepLink: {
		"result": {"ok", "error"},
	},
	EventWinAuth: {
		"flow":  {"auto", "manual"},
		"stage": {"trying", "failed", "ok", "relay_trying", "relay_ok", "all_unreachable", "saved_key_invalid", "no_saved_key"},
	},
	EventWinNodeId: {
		"stage": {"load_failed", "loaded"},
	},
	EventWinDht: {
		"stage": {"started", "listen_failed", "bad_node_id", "relay_server_punch_failed", "relay_server_serving"},
	},
	EventWinGeo: {
		"stage": {"persisted_country_loaded", "explicit_region_applied", "device_country_applied", "device_country_stored"},
	},
	EventWinAutostart: {
		"result": {"ok", "error"},
	},
	EventWinFirewall: {
		"stage": {"exe_path_failed", "add_failed", "added", "delete_failed", "removed"},
	},
	EventWinConnectReauth: {
		"stage": {"trying", "direct_failed", "ok"},
	},
	EventWinConnectUdpRelay: {
		"stage": {"punch_failed", "login_failed", "ok"},
	},
	EventWinConnectRelays: {
		"stage": {"fetching", "save_failed", "fetch_failed", "probing_data_plane", "building_paths"},
	},
	EventWinDhtAnnounce: {
		"stage": {"probe_failed", "sign_failed", "entry_set", "all_probes_failed"},
	},
	EventWinRelayClient: {
		"stage": {"punching", "punch_failed", "established"},
	},
	EventWinMyip: {
		"result": {"ok", "error"},
	},
	EventWinCountryPredetect: {
		"stage": {"skipped", "waiting", "detected", "switching", "timed_out"},
	},
	EventWinPathPick: {
		"stage": {"udp_relay", "tcp_relay", "none"},
	},
	EventWinUdpUpgrade: {
		"stage": {"skipped_tcp_available", "upgraded"},
	},
	EventWinPoolBuild: {
		"stage": {"topup_needed", "topup_added", "auth_failed", "dialer_failed", "control_added", "building", "pool_size", "pool_ready", "hooks_attached"},
	},
	EventWinTunnelReauth: {
		"stage": {"warning", "recovered", "fatal", "server_unavailable_reconnect", "credentials_rejected"},
	},
	EventWinTunnelEvict: {
		"reason": {"first_fail", "data_fail", "udp_fail", "auth_fail", "pool_empty", "last_dialer"},
	},
	EventWinTunnelSilentRefresh: {
		"stage": {"started", "dialer_failed", "succeeded", "attempt_failed", "timed_out"},
	},
	EventWinSocks5TunSetup: {
		"stage": {"socks5_starting", "socks5_listening", "tun_starting", "tun_failed", "routes_applying", "routes_failed", "connected", "dns_pin_failed", "watchdog_write_failed"},
	},
	EventWinDoh: {
		"trigger": {"connect", "toggle"},
		"stage":   {"configuring", "netsh_unavailable", "proxy_failed", "netsh_active", "disabled"},
	},
	EventWinConnectFinalize: {
		"stage": {"starting_server", "quic_blocked", "realtime_udp_ready", "realtime_udp_unavailable", "server_started"},
	},
	EventWinPoolRefill: {
		"stage": {"below_target", "auth_failed", "dialer_failed"},
	},
	EventWinCountryChange: {
		"stage": {"changed", "region_set", "pool_complete_after_retry", "cidr_init_skipped"},
	},
	EventWinDisconnect: {
		"stage": {"auto_reconnect", "user_initiated", "watchdog_write_failed", "disconnected"},
	},
	EventWinSettingsChange: {
		"setting": {"block_quic", "region"},
	},
	EventWinPersistFailed: {
		"what": {"device_id", "country"},
	},
	EventWinSingleInstance: {
		"stage": {"terminating_other", "kill_failed", "old_terminated"},
	},
	EventWinGeoDetect: {
		"source": {"gps", "system_locale", "timezone"},
	},
	EventWinWindowCreateFailed: {
		"window": {"key_dialog", "notification"},
	},
	EventWinWatchdogCleanup: {
		"stage": {"restoring", "routes_removed"},
	},
	EventWinPower: {
		"stage": {"wake", "class_register_failed", "window_create_failed", "watcher_started"},
	},
	EventWinBrowserWindow: {
		"stage": {"panic", "creating", "init_failed", "ready", "wndproc_panic", "entering_run"},
	},
	EventWinDnsConfig: {
		"stage": {"doh_enabled", "cleanup_none_found", "cleanup_removed", "doh_fallback_active", "fallback_stopped", "fallback_stop_failed", "doh_removed", "doh_remove_failed"},
	},
	EventWinDohProxy: {
		"stage": {"listening", "stopped", "recv_error", "forward_failed", "write_failed", "resolved"},
	},
	EventWinWatchdogProcess: {
		"stage": {"started", "events_create_failed", "pipe_unavailable", "stale_state_cleanup", "main_handle_failed", "probe_restart", "clean_shutdown_signaled", "clean_shutdown_timeout", "lastalive_stale_wait", "lastalive_frozen_kill", "pipe_heartbeat_stale", "main_exited", "exiting_clean", "ota_restart", "crash_cleanup", "restart_giveup"},
	},
	EventWinWatchdogProbe: {
		"stage": {"all_unreachable", "confirmed_dead"},
	},
	EventWinWatchdogMainAttach: {
		"stage": {"attached_existing", "started_fresh", "start_failed", "handle_failed", "already_running", "stale_pid_reused", "restarted", "restart_failed"},
	},
	EventWinCoreProxy: {
		"stage": {"starting", "invalid_key", "no_server_addrs", "auth_failed", "all_controls_unreachable", "auth_ok", "socks5_listen_failed", "socks5_ready", "shutting_down", "recovery_reachable"},
	},
	EventWinSetIcon: {
		"stage": {"start", "created"},
	},
	EventWinTrayLclickInstall: {
		"stage": {"searching", "not_found", "found", "panic", "systray_msg", "click_detected", "subclassed"},
	},
	EventWinSplash: {
		"stage": {"start", "decode_failed", "decoded", "dib_failed", "dib_created", "window_failed", "window_created", "update_layered", "shown", "timer_set", "quit", "dismissed_timer", "dismissed_click", "done", "font_bold_failed", "font_regular_failed", "title_face_failed", "version_face_failed"},
	},
	EventWinRoutes: {
		"stage": {"server_resolved", "gateway_found", "local_ip_found", "local_ip_failed", "server_bypass_added", "server_bypass_failed", "tun_iface_found", "split_route_added", "ipv6_disabled_blocking", "ipv6_block_failed", "ipv6_block_ok", "ipv6_route_added", "ipv6_route_failed", "bypass_added", "bypass_failed", "ipv6_unblock_failed", "ipv6_unblocked"},
	},
	EventWinTrayMenuAction: {
		"action": {"open_window", "login", "logout", "connect", "disconnect", "doh_toggle", "doh_now", "block_quic_toggle", "block_quic_now", "region_auto", "region_ru", "region_eu", "region_us", "region_cn", "region_other", "connect_ch", "disconnect_ch", "reconnect_ch", "update_notification", "update_click", "login_ch", "logout_ch", "quit_ch", "about", "quit"},
	},
	EventWinTrayConnect: {
		"stage": {"login_failed", "already_in_progress", "starting", "ui_hiding_connect", "panic", "error_entering", "failed", "ui_restore_connect", "requeue_pending", "disconnect_during_connect", "requeue_after_disconnect", "ui_pending_restore", "success"},
	},
	EventWinTrayDisconnect: {
		"stage": {"drained_stale", "starting", "not_connected_pending", "connecting_to_disconnecting", "hiding_actions", "hung_forcing_reset", "done", "restoring_idle", "showing_connect"},
	},
	EventWinTrayState: {
		"stage": {"login_error", "reconnect_suppressed", "power_wake_debounced", "power_wake_healthy_skip", "quit_disconnect_timeout", "update_reset", "status_change", "watchdog_stuck", "error_state_connection_lost"},
	},
	EventWinUiwindowMenu: {
		"action": {"connect", "disconnect", "checkbox_toggle", "region_combo", "login", "logout", "connect_menu", "disconnect_menu", "doh_toggle", "quic_toggle", "about", "update", "quit"},
	},
	EventWinUiwindowLifecycle: {
		"stage": {"panic", "class_icon", "start", "run_panic", "hicon", "window_failed", "hwnd_created", "initial_icon", "ready", "message_loop_exited", "bg_decode_failed", "dib_failed", "bg_ready", "cat_decode_failed", "cat_bg_decode_failed", "club_theme", "status_dropped", "status"},
	},
	EventAuthLoginStage: {
		"stage": {"dns_start", "dns_done", "connect_start", "connect_done", "tls_start", "tls_done", "wrote_request", "got_first_byte", "done", "error"},
	},
	EventWinDialogAction: {
		"action": {"key_dialog_scan_image", "key_dialog_ok", "key_dialog_ok_invalid", "key_dialog_cancel", "key_dialog_login_instead", "have_key_yes", "have_key_no", "login_dialog_ok", "login_dialog_ok_incomplete", "login_dialog_cancel", "login_dialog_keymode", "login_dialog_password_toggle", "update_dialog_yes", "update_dialog_no"},
	},
	EventMacTrayAction: {
		"action": {"open_window", "login", "logout", "connect", "disconnect", "doh_toggle", "block_quic_toggle", "region_auto", "region_ru", "region_eu", "region_us", "region_cn", "region_other", "update_click", "about", "share_logs", "quit"},
	},
	EventMacDialogAction: {
		"action": {"key_dialog_connect", "key_dialog_cancel", "key_dialog_scan_image", "key_dialog_paste", "have_key_yes", "have_key_no", "login_dialog_login", "login_dialog_cancel", "login_dialog_keymode", "login_dialog_password_toggle", "window_connect", "window_disconnect", "window_settings_changed", "window_recommend_submit", "window_club_theme_preview", "update_dialog_now", "update_dialog_later", "legacy_key_dialog_ok", "legacy_key_dialog_cancel"},
	},
	EventLinuxTrayAction: {
		"action": {"login", "logout", "connect", "disconnect", "doh_toggle", "block_quic_toggle", "region_auto", "region_ru", "region_eu", "region_us", "region_cn", "region_other", "update_click", "open_window", "share_logs", "about", "quit"},
	},
	EventLinuxDialogAction: {
		"action": {"have_key_yes", "have_key_no", "credential_login", "key_mode_switch", "activate_key", "window_connect", "window_disconnect", "window_settings_changed", "window_club_theme_preview", "window_recommend_submit"},
	},
	EventAndroidUiAction: {
		"action": {"disable_ipv6_toggle", "disable_udp_toggle", "disable_quic_toggle", "disable_bypass_toggle", "share_logs", "update_menu_open", "update_dialog_install", "update_dialog_later", "logout_menu_open", "logout_confirm_remove", "logout_confirm_cancel", "recommend_menu_open", "recommend_send", "recommend_cancel", "club_theme_regular", "club_theme_catclub", "club_theme_elite", "activate_key", "have_key_yes", "have_key_no", "key_entry_login_instead", "switch_to_key_entry", "toggle_password", "do_login", "scan_qr", "scan_file", "apps_select_all", "apps_deselect_all", "apps_row_toggle", "browse_nav_back", "browse_nav_forward", "browse_reload", "browse_tabs_open", "browse_tab_new", "browse_tab_close", "browse_tab_switch", "browse_retry_page", "battery_opt_allow", "battery_opt_not_now"},
	},
	EventIosUiAction: {
		"action": {"connect", "disconnect", "logout_menu_open", "logout_confirm_remove", "logout_confirm_cancel", "key_entry_login_instead", "have_key_yes", "have_key_no", "switch_to_key_entry", "toggle_password", "credential_login_submit", "scan_qr", "scan_file", "update_banner_tap", "share_logs", "browser_back", "browser_forward", "browser_reload", "browser_tabs_open", "browser_tab_switch", "browser_tab_new", "browser_tab_close", "browser_url_submit", "qr_scan_cancel", "qr_code_scanned", "update_notification_tap"},
	},
}

// ipFields marks fields whose value is a literal IP address (never a
// hostname or host:port combo) -- Emit() encodes these as raw 4/16-byte
// CBOR byte strings instead of dotted/colon text.
var ipFields = map[Event]map[string]bool{}
