// The Tunnel Cat Project
// Copyright (C) NavLink, 2026
// Лицензировано под лицензией Apache 2.0

// Hand-written C declarations mirroring cmd/lib-ios's //export signatures —
// preferred over cgo's autogenerated header, which pulls in cgo-internal
// GoString/GoInt typedefs.
//
// Build the archive first (from the repo root):
//
//   GOOS=ios GOARCH=arm64 CGO_ENABLED=1 CC=<clang> \
//     go build -buildmode=c-archive -o libtunnelcat_core_arm64.a ./cmd/lib-ios
//
// Then link libtunnelcat_core_arm64.a into your Xcode target's
// OTHER_LDFLAGS / LIBRARY_SEARCH_PATHS and set this file as the target's
// SWIFT_OBJC_BRIDGING_HEADER.

#include <stdlib.h>

// TCStart logs in and starts a local SOCKS5 server.
// Returns 0 on success, -1 on failure (check TCGetStatus for the error).
extern int TCStart(char *server, char *apiKey, char *username, char *password,
                    char *logDir, char *dataDir);

// TCStop tears down the SOCKS5 server and clears session state.
extern void TCStop(void);

// TCGetStatus returns a heap-allocated JSON C-string:
// {"state":"idle"|"connecting"|"connected"|"error","error":"..."}
// Caller must free the result with TCFreeString.
extern char *TCGetStatus(void);

// TCFreeString frees a string returned by TCGetStatus.
extern void TCFreeString(char *s);

// TCGetSocksPort returns the local SOCKS5 listener's port, or 0 if not
// currently listening.
extern int TCGetSocksPort(void);

// TCReconnect re-runs Login() against the same credentials passed to the
// last successful TCStart.
extern void TCReconnect(void);
